### ISSUE TITLE
Suggest not to lock @types/react

### ISSUE THREAD

**Issue by foray1010** [testing-library/react-hooks-testing-library#104]
### What is your question:

as this library locked version of `@types/react`, I expect we will keep seeing this kind of error as `@types/react` export global type
<img width="1199" alt="Screen Shot 2019-06-22 at 8 42 45 AM" src="https://user-images.githubusercontent.com/3212221/59957329-c66ed380-94c9-11e9-915c-ee6df6376bf6.png">

It will be very annoying cause user need to sync the `@types/react` version with this library in order to avoid this error

could we use `^16.8.22` instead?

**Comment by mpeyper** [comment]
Yes. Can you make a PR to fix please.
