### ISSUE TITLE
How to turn off nighttime mode in the docs

### ISSUE THREAD

**Issue by iqbal125** [testing-library/react-hooks-testing-library#107]
A way to turn off the nighttime mode. Perhaps an option to switch to a lighter background color. Darker background makes it very hard to read the text, especailly if you are using flux like I am.

**Comment by mpeyper** [comment]
Hey @iqbal125,

We're using [Docz](https://www.docz.site/)'s default [dark theme](https://github.com/pedronauck/docz/tree/master/core/docz-theme-default).  I'm not aware of any way to have a theme toggle or anything like that with the setup we are using.

I'm more than happy if someone wants to explore this and/or change it to a better theme (or create one?) if there are some readability issues.  I'm even happy if someone wants to switch out Docz for something else altogether if it makes this sort of thing easier.

**Comment by mpeyper** [comment]
I've noted this in #19 so I'll close this one now.  Please add any other issues you may have with the current docs to that one.
