### ISSUE TITLE
Curious why setCount being called in the useCallback() hook. 

### ISSUE THREAD

**Issue by iqbal125** [testing-library/react-hooks-testing-library#108]
### What is your question:

I was reading the docs and confused why is setCount being called in the useCallback() hook. 

>   const [count, setCount] = useState(0)
>   const increment = useCallback(() => setCount((x) => x + 1), [])
>   return { count, increment }

I read this article by kent c dodds that explains calling setState in the useCallback hook is not effective. I was wondering if there was a reason related to this that Im not getting. 

https://kentcdodds.com/blog/usememo-and-usecallback

 Im just trying to learn thank you.

**Comment by mpeyper** [comment]
Hi @iqbal125,

Interesting read.  There were 2 parts to it when originally coming up with that example:

1. It used another hook function so there were more ways it could evolve as you learn more features of the library while going through the docs
2. I didn't want to be accused of causing unintentional rerenders by creating new functions each render
   * I'd already been [called out](https://dev.to/josepot/react-s-bogus-setstate-anti-pattern-287e) on not doing it "properly" once before

The effect of unintentional rerenders on performance has been the topic of much discussion a lot recently, by @kentcdodds and others, which is showing that in most cases, the premature optimisation of `useCallback` and `useMemo` can actually have a negative effect on performance.  This is not something I have measured myself, so I cannot say one way or another if the code in the example is better or worse with the `useCallback` or not.

So I guess the answer to your question is that I'm still learning, just like you, and maybe it shouldn't be wrapped in `useCallback` 😅 

If you want to rework the examples in the docs to not include this, but still get the lessons accross, I'd happily consider it as a PR.
