### ISSUE TITLE
Duplicated identifier Errors with TypeScript

### ISSUE THREAD

**Issue by fxOne** [testing-library/react-hooks-testing-library#110]
- `react-hooks-testing-library` version: 1.0.4
- `react-test-renderer` version: 16.8.6
- `react` version: 16.8.17
- `@types/react` version: 16.8.17
- `typescript` version: 3.3.3333
- `node` version: 11.9.0
- `npm`  version: 6.7.0

### Relevant code or config:

\-

### What you did:

I installed the latest Version of `react-hooks-testing-library` and got after a `typecheck` the following error.

### What happened:

```
node_modules/@testing-library/react-hooks/node_modules/@types/react/index.d.ts:2817:14 - error TS2300: Duplicate identifier 'LibraryManagedAttributes'.

2817         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                  ~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@types/react/index.d.ts:2816:14
    2816         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                      ~~~~~~~~~~~~~~~~~~~~~~~~
    'LibraryManagedAttributes' was also declared here.

node_modules/@testing-library/react-hooks/node_modules/@types/react/index.d.ts:2881:13 - error TS2717: Subsequent property declarations must have the same type.  Property 'iframe' must be of type 'DetailedHTMLProps<IframeHTMLAttributes<HTMLIFrameElement>, HTMLIFrameElement>', but here has type 'DetailedHTMLProps<IframeHTMLAttributes<HTMLIFrameElement>, HTMLIFrameElement>'.

2881             iframe: React.DetailedHTMLProps<React.IframeHTMLAttributes<HTMLIFrameElement>, HTMLIFrameElement>;
                 ~~~~~~

node_modules/@types/react/index.d.ts:2816:14 - error TS2300: Duplicate identifier 'LibraryManagedAttributes'.

2816         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                  ~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@testing-library/react-hooks/node_modules/@types/react/index.d.ts:2817:14
    2817         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                      ~~~~~~~~~~~~~~~~~~~~~~~~
    'LibraryManagedAttributes' was also declared here.
```

### Problem description:

The issue is that I use the  `@types/react: 16.8.17` while this library uses `@types/react: 16.8.22` which results in 2 different installed `@types/react` versions. After updating to the latest `@types/react` the problem was solved.

### Suggested solution:
There should be any typescript dependency installen when I install this package.

**Comment by mpeyper** [comment]
We briefly had s release where we published a version that had a pinned version of the `@types/react` dependency, but we fixed that in `1.0.4` so I'm not sure why, assuming you also use a semver range, that you would end up with a duplicate.

None-the-less, as part of our package, we require the react type definitions, so we need to include it as a dependency.  I'm not sure what the alternatives are that could avoid this circumstance from occurring?

**Comment by fxOne** [comment]
I think the problem should be solve by moving the `@types` definitions from the `dependencies` to the `devDependencies` in the `package.json`.

See also: https://docs.npmjs.com/files/package.json#devdependencies

**Comment by mpeyper** [comment]
If my [type definitions have a dependency on another packages type definitions](https://github.com/testing-library/react-hooks-testing-library/blob/master/typings/index.d.ts#L1), then should they not be a dependency of my package?  

Genuinely asking as I'm not a typescript use myself.

I can see that they could be considered a [peer dependency](https://docs.npmjs.com/files/package.json#peerdependencies), similar to `react` itself, but this is troublesome for non-typescript users as they will get a peer dependency if they don't install it, even though they don't need it.  Perhaps this is a case for [optional dependencies](https://docs.npmjs.com/files/package.json#optionaldependencies)?

**Comment by fxOne** [comment]
I'm also new to TypeScript but when i look around I can only find projects which have their `@types` ind the `devDependencies` e.g.: https://github.com/jaredpalmer/formik/blob/4e629c9938ec628452af2ff2c2d537b795de1f56/package.json#L59

When I use TypeScript I already have the `@types` installed as I need them for development and when I don't use TypeScript I dont want to have the packges installed at all.

**Comment by mpeyper** [comment]
Sorry for the delayed response.

You would only have the dependency installed if it was a library you were already using (which is likely in this case, but potentially not for all libraries out there).  Assuming the depenency is a a compatible sevmer range, it the npm install should resolve to the same instance.  If they are not compatibile, then you would have a problem anyway, even if it was a `peerDependency`.

Conversely, the cost of installing some type dependencies when you don't want them is pretty small.

**Comment by fxOne** [comment]
After doing some more research I found this ticket which says that it is the correct way to use `dependency` to add the `@types`: https://github.com/microsoft/types-publisher/issues/81

At the end there are also some people which have compatibility issues when the `@types` are added to `dependency` so that they add them to `devDependency`.

Is it possible to change the `"@types/react": "^16.8.22"` `dependency` to `"@types/react": ">=16.8.0"` as this was the version when react hooks was introduced and we can use this great testing library?

**Comment by mpeyper** [comment]
From my understanding of semver ranges, `">=16.8.0"` would match any newer version, whereas `"^16.8.0"` would only match `16.x.x` versions, which is probably safer to prevent breaking changes biting our users.

I use [a bot](https://renovatebot.com/) for keeping dependency versions up to date, so I'm not sure if that will roll through a push it back up to latest again if we open up the range a bit more.

**Comment by fxOne** [comment]
As far as I can see you can configure your bot to exclude dependencies: [enable](https://renovatebot.com/docs/configuration-options/#enabled)
Also you more configuration options with the [packageRules](https://renovatebot.com/docs/configuration-options/#packagerules).

**Comment by tcoldmf** [comment]
I have the same problem.

**Comment by mpeyper** [comment]
I have updated the version range in version 2 to be `">=16.9.0"` with the intention if leaving at the minimum version for async `act` calls (which we now rely on so it can't be `">=16.8.0"` like suggested above.

I'll close this now, but please let me know if this is still causing issues so we can try again at fixing it.

**Comment by filame** [comment]
I use version 2.0.1 and the issue still appears.

**Comment by mpeyper** [comment]
Clearly there is more to be done here.

@atomicpages (or anyone), are you able to run [`npm dedupe`](https://docs.npmjs.com/cli/dedupe.html) and see if that helps?

**Comment by mpeyper** [comment]
For anyone following this issue, I'm thinking we're going to follow the [path of some other testing-library packages](https://github.com/testing-library/react-testing-library/pull/437) and move the types to DefinitelyTyped and make them a dependency here.

To be honest, I don't know how it is any different from what we're currently doing (other than moving the dependencies in a layer) or that it will make this situation any better, but I'm not seeing any complaints on the approach in the other package repos.

Happy for anyone to take the reigns on either the DefinatelyTyped side or the relevant changes here.

**Comment by mpeyper** [comment]
For anyone following this, I've created the PR to add the type definitions to DefinitelyTyped -> https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38715

**Comment by mpeyper** [comment]
The DefinitelyTyped changes went out in v2.0.2.  Please update and let me know if there are still any issues.

**Comment by felixfbecker** [comment]
Could you document this as a breaking change in the 2.0.2 patch notes?

**Comment by mpeyper** [comment]
Apologies about missing the release notes (I forgot to push the tags so didn't have that as a trigger to update them).  [I've updated them now](https://github.com/testing-library/react-hooks-testing-library/releases/tag/v2.0.2).

I went with a non-breaking change version bump as the type definitions have not changed, just moved and it is hopefully resolving an issue some people are seeing on the current version.  For anyone not having this issue, there should be no changes required.

**Comment by iuliuvisovan** [comment]
Did you mistakenly install any @testing-library/ dependencies to 'dependencies' instead of 'devDependencies'?

**Comment by pvinis** [comment]
I see this closed with nothing changed?

`@types/react` are still in `dependencies` instead of `devDependencies`. This is still causing problems. I thought by now this is a known thing, that types go in the devdeps or peerdeps, never in the deps.

Any suggestions on how to use this library without getting silly errors like
```

node_modules/@testing-library/react-hooks/node_modules/@types/react/index.d.ts:3090:13 - error TS2717: Subsequent property declarations must have the same type.  Property 'colgroup' must be of type 'DetailedHTMLProps<ColgroupHTMLAttributes<HTMLTableColElement>, HTMLTableColElement>', but here has type 'DetailedHTMLProps<ColgroupHTMLAttributes<HTMLTableColElement>, HTMLTableColElement>'.

3090             colgroup: React.DetailedHTMLProps<React.ColgroupHTMLAttributes<HTMLTableColElement>, HTMLTableColElement>;
                 ~~~~~~~~

  node_modules/@types/react/index.d.ts:2979:13
    2979             colgroup: React.DetailedHTMLProps<React.ColgroupHTMLAttributes<HTMLTableColElement>, HTMLTableColElement>;
                     ~~~~~~~~
    'colgroup' was also declared here.
```
?

**Comment by mpeyper** [comment]
Hi @pvinis,

If you have any links to documentation or even articles on the best practice around this subject I'll happily read them and reconsider, however I did put quite a bit of effort into trying to understand the behaviour of this and replicating how type dependencies are when built by the DefinatelyTyped repo and am fairly comfortable with the approach we are currently taking.

I am aware of an issue with dependency resolution in yarn vs npm (#610) so perhaps that is what you are running into?

If you want to share more details about your setup (perhaps in a new issue) I'll happily dig in and see if there is a simple fix or workaround for you.

**Comment by pvinis** [comment]
I guess the one I can point to is https://github.com/microsoft/types-publisher/issues/81#issuecomment-234051338. A lot of other discussions are basically this:
- If people importing your lib cannot use it without another dep, only then put it in deps.
- Otherwise, devdeps.

My question would be, do we need that in there?

I will try to do a RN init and and try to repro.

**Comment by pvinis** [comment]
Hm... in a new repo, I don't get the same problems, but I also see that it's using react 17. I will look into it, maybe our repo with 16 has some issues?

**Comment by pvinis** [comment]
Cleaning node_modules fixed it 🙈.

**Comment by nomasprime** [comment]
Personally, I just avoid TS at every possible opportunity, the stuff of nightmares.
