### ISSUE TITLE
Uses deprecated package name react-testing-library as dependency over @testing-library/react

### ISSUE THREAD

**Issue by lad475** [testing-library/react-hooks-testing-library#130]
- `react-hooks-testing-library` version: 1.1.0
- `react-test-renderer` version: 8.0.5 (@testing-library/react)
- `react` version: 16.8.6
- `node` version: 12
- `npm` (or `yarn`) version: 6.9 (npm)

### Relevant code or config:

```js
import { renderHook, act } from '@testing-library/react-hooks';
```

### What you did:

Was writing tests for custom hooks

### What happened:

Cannot find module 'react-test-renderer' from 'index.js'

   > 1 | import { renderHook, act } from '@testing-library/react-hooks';

### Reproduction:

Create a react app and install @testing-library/react and @testing-library/react-hooks, and observe that @testing-library/react-hooks seems to require the old package name, react-testing-library

### Problem description:

I want to use the latest versions of everything, and not the deprecated package name

### Suggested solution:

Change all instances of react-testing-library with @testing-library/react

**Comment by lad475** [comment]
my bad- I must be too tired right now.  I read test-render as testing-library.  Closing this.

**Comment by alienzoe** [comment]
@lad475 I was having the same issue right now. What was the fix for this?

**Comment by mpeyper** [comment]
Hi @alienzoe. We use `react-test-renderer` not `react-testing-library` or `@testing-library/react` for rendering. Please ensure it is installed at the same version as `react` in your project.
