### ISSUE TITLE
Incorrest state when testing with renderHook

### ISSUE THREAD

**Issue by kostrse** [testing-library/react-hooks-testing-library#148]
I was trying to test behavior of the `useAsync` hook using the `renderHook` from the testing-`library/react-hooks`, and found the following issues (which is probably I'm trying to use the library in a wrong way).

First, when hook returns it's initial state, it returns **initialValue** (as expected), but it also indicates that the promise has been already resolved:

```ts
it('should set into proper initial state', async () => {
    const asyncFunc = () => Promise.resolve(2);

    const { result } = renderHook(() => useAsync(asyncFunc, { initialValue: 1 }));

    expect(result.current.value).toEqual(1);
    expect(result.current.isResolved).toBe(false); // FAILS, ALREADY RESOLVED
});
```

I expected it to be either `{ data: 1, isResolved: false }`, or `{ data: 2, isResolved: true }`.

Second issue, is that for some reason the `waitForNextUpdate` never resolve:

```ts
it('should resolve resolved promise', async () => {
    // already resolved
    const asyncFunc = () => Promise.resolve(2);

    const { result, waitForNextUpdate } = renderHook(() => useAsync(asyncFunc, { initialValue: 1 }));

    expect(result.current.value).toEqual(1);

    await waitForNextUpdate(); // NEVER RESOLVE
});

it('should resolve asynchronous promise', async () => {
    // will resolve in 50ms
    const asyncFunc = () => new Promise(resolve => setTimeout(resolve, 50)).then(() => 2);

    const { result, waitForNextUpdate } = renderHook(() => useAsync(asyncFunc, { initialValue: 1 }));

    expect(result.current.value).toEqual(1);

    await waitForNextUpdate(); // NEVER RESOLVE
});
```

This is probably related to the first issue - promise is in resolved state already but the value from the promise wasn't set.

**Comment by mpeyper** [comment]
Can you share the `useAsync` hook code as well please? (Preferably in a codesandbox)

**Comment by kostrse** [comment]
I'm sorry, I had intention to post it to [react-async](https://github.com/ghengeveld/react-async), posted by mistake here. I believe the issue is with `react-async`, not `@testing-library/react-hooks`.
