### ISSUE TITLE
TypeError: Cannot read property 'current' of undefined

### ISSUE THREAD

**Issue by samuherek** [testing-library/react-hooks-testing-library#151]
- `@testing-library/react-hooks` version: 2.0.1
- `react-test-renderer` version: 16.8.6
- `react` version:  16.8.6
- `node` version: v12.9.0
- `npm` version: 6.10.2

### Relevant code or config:

```js
import { renderHook } from '@testing-library/react-hooks';
import { useMyHook } from '../useMyHook';

test('useMyHook initializes correctly', () => {
  const { result } = renderHook(() => useMyHook());
});
```

### What you did:
simply run the tests `react-scripts test --env=jsdom --watchAll`

### What happened:
It throw an error saying it can not read property 'current'. I searched most places and I didn't see anyone else getting the same error. 
```
TypeError: Cannot read property 'current' of undefined

      12 | test('useMyHook initializes correctly', () => {
    > 13 |   const { result } = renderHook(() => useMyHook());
                                ^
```

### Reproduction:
https://codesandbox.io/s/kind-agnesi-v9ren

### Problem description:
Because it doesn't seem to be possible to test hooks with this library.
Is there something missing in the docs that needs to be done as an extra step?

**Comment by mpeyper** [comment]
The sandbox you linked has misatching versions for `react`, `react-dom` and `react-test-renderer`.

Updating them all to `16.9.0` makes the test pass.  https://codesandbox.io/s/lively-moon-05d78

**Comment by JackHowa** [comment]
thanks @mpeyper. can confirm 

was seeing error with: 

```
    "react": "^16.6.1",
    "react-test-renderer": "^16.8.6",
    "@testing-library/react": "^9.1.3",
    "react-dom": "^16.6.1",
```

no longer with: 

```
    "react": "^16.9.0",
    "react-test-renderer": "^16.9.0",
    "@testing-library/react": "^9.1.3",
    "react-dom": "^16.9.0",
```

**Comment by jtaylor1989** [comment]
make sure to install the same verions of react and react-test-renderer (e.g. 16.8.3).

**Comment by afternoon2** [comment]
I have following versions:
```
"react": "^17.0.2",
"react-dom": "^17.0.2",
"react-test-renderer": "^17.0.2",
```

but still got the error `TypeError: Cannot read property 'createElement' of undefined` 😒

**Comment by mpeyper** [comment]
Hey @afternoon2, that looks like a different issue to this one.  Do you want to [raise a new ticket](https://github.com/testing-library/react-hooks-testing-library/issues/new?assignees=&labels=bug&template=---bug-report.md&title=) so we don't spam everyone here with notifications while we work through it?

It's likely also version issue, so the results from `npm ls react react-dom react-test-renderer` will help debugging this.

**Comment by tychota** [comment]
(@mpeyper For users that may encounter this issue.)

I did encounter something similar when following storybook tutorial.

![image](https://user-images.githubusercontent.com/13785185/182657440-ca305c0f-eff5-491f-be0d-98871377ffb5.png)

I fixed it using resolutions in package.json

![image](https://user-images.githubusercontent.com/13785185/182657609-f101f878-461e-4682-aed2-26d944150ef0.png)

**Comment by Sid-Turner-Ellis** [comment]
If you started getting this error after upgrading to react 18 then make sure you have converted `import {renderHook} from @testing-library/react-hooks` to `import {renderHook} from @testing-library/react`

**Comment by candymd** [comment]
> If you started getting this error after upgrading to react 18 then make sure you have converted `import {renderHook} from @testing-library/react-hooks` to `import {renderHook} from @testing-library/react`

Thank you! This was exactly my issue.
