### ISSUE TITLE
More elegant renderHook interface.

### ISSUE THREAD

**Issue by PolarbearDK** [testing-library/react-hooks-testing-library#160]
### Describe the feature you'd like:

I think the renderHook interface is a bit clumbersome, especially when working with custom hooks with arguments.

### Suggested implementation:

I have created a Typescript wrapper to simplify the unit testing code

```Typescript

// Test utilty for custom hooks with effects.
// Usage:
//       const hook = renderCustomHook(useMyHook, TypedArd1, TypeArg2, TypedArg3...);
//
// assert results from: hook.result
// use hook.rerender(typed arguments) to update hook.
export function renderCustomHook<T extends any[], R>(
  theHook: (...args: T) => R,
  ...args: T
): {
  readonly result: HookResult<R>;
  readonly waitForNextUpdate: () => Promise<void>;
  readonly unmount: () => boolean;
  readonly rerender: (...args: T) => void;
};
export function renderCustomHook(theHook: (...args: any[]) => any, ...args: any[]) {
  const hook = renderHook((param: { props: any[] }) => theHook(...param.props), {
    initialProps: { props: args },
  });
  return { ...hook, rerender: (...args: any[]) => hook.rerender({ props: args }) };
}
```

### Describe alternatives you've considered:

Would it be possible to include something like this in the library?

**Comment by PolarbearDK** [comment]
Related to #56

**Comment by mpeyper** [comment]
I'm not particularly fond of the `const hook = renderHook(someHook, arg1, arg2, arg3)` interface.  One of my design goals with this library is to use the hook like you would in your component.  This means calling it yourself with the arguments you want ti to have.

An option I have considered would be do something like:

```js
const testSomeHook = wrapHook(someHook)

const hook = testSomeHook(arg1, arg2, arg3)
```

Which is a similar concept, but feels more like just calling the function than your example.

I'm going to close this and move the suggestion to #56, just to keep them all in one place.

**Comment by PolarbearDK** [comment]
Thanks. Sorry I missed the RFC post.
