### ISSUE TITLE
Remove unnecessary nesting

### ISSUE THREAD

**Issue by pelotom** [testing-library/react-hooks-testing-library#180]
It seems like the `result` field creates an unnecessary level of nesting that makes tests awkwardly verbose. Why not get rid of `HookResult` and move `current` and `error` into the `RenderHookResult` interface? Currently in an effort to reduce verbosity I find myself destructuring the output of `renderHook` like so:

```ts
it('works', () => {
  const { result: $, waitForNextUpdate } = renderHook(useMyHook);
  act($.current.someAction);
  await waitForNextUpdate();
  expect($.current.value).toBe(42);
});
```

whereas with my proposed change one could simply write

```ts
it('works', () => {
  const $ = renderHook(useMyHook);
  act($.current.someAction);
  await $.waitForNextUpdate();
  expect($.current.value).toBe(42);
});
```

**Comment by mpeyper** [comment]
The API follows the [direction set by `react-testing-library`](https://testing-library.com/docs/react-testing-library/api#render) where the `container` (or in our case, `result`), is intended to be destructured alongside any helpers for use in the test.

For me that approach has 2 benefits:

1. It's more explicit which parts of the API your test depends on (it's almost like an `import` statement`
2. We have to worry less about any implicit correlation users would make between the result and the helpers (for example, `waitForNextUpdate` does not wait for the next change to the `results.current`, but rather the next render of the underlying component).  I also have a plan to include a `container` value that represents the rendered component in the near future, which would further complicate things.

I'm not sure, but I think I saw someone tweeting that the following syntax _might_ work (I'll have to run some tests to check):

```js
it('works', () => {
  const result, { waitForNextUpdate } = renderHook(useMyHook);
  act(results.current.someAction);
  await waitForNextUpdate();
  expect(result.current.value).toBe(42);
});
```

which would be ideal, as this is conceptually how I see the API.

I'll close this issue for now, as I don't see us making any major API changes based on personal preference, but please feel free to continue the discussion here.
