### ISSUE TITLE
Make it much more prominent that only >= react@16.9.0 is supported

### ISSUE THREAD

**Issue by sgb-io** [testing-library/react-hooks-testing-library#183]
Right now, this is mentioned like a footnote in the readme. I invested time to write tests on parts of our app using hooks, only to later discover that even with a quite modern version of React (16.8.6), the tests work, but the peer dependency requirement means I get two versions of React and therefore my types collide.

I think it would be courteous to make this more prominent at the top of the README.

**Comment by mpeyper** [comment]
Hi @sgb.io,

Sorry if you lost any time with this. PRs are always welcome for improving the documentation.

I haven't yet seen the peer dependency be an issue for people. In fact, I didn't think it would cause a duplicate version issue at all as the whole point of a peer dependency is that the user must install the dependency themselves and you just get install time warnings about versions mismatches.

You mentioned your types colliding, so this sounds more like the existing issue around how to deal with type dependencies, #110.  If that's the case, I think we can close this issue and keep track of it in that one.

**Comment by sgb-io** [comment]
Thanks @mpeyper, I think relocating the types is the right solution. The current collision problem means that _effectively_ only 16.9.0+ is supported, but it sounds like your suggestion in #110 could solve the problem and therefore make more versions compatible for TypeScript users.

**Comment by sgb-io** [comment]
Actually, I realised that the dependency on React 16.9.0 is a hard one, since you're using `act`. Therefore this could still be a documentation improvement.

**Comment by mpeyper** [comment]
I've tried to make it stand out in the docs a bit more:

* [README](https://github.com/testing-library/react-hooks-testing-library#peer-dependencies)
* [Installation Docs](https://react-hooks-testing-library.com/#peer-dependencies)
* [NPM page](https://www.npmjs.com/package/@testing-library/react-hooks#peer-dependencies)
* NPM CLI
   ```sh
   > npm i react@16.8.6 react-test-renderer@16.8.6 @testing-library/react-hooks
   npm WARN @testing-library/react-hooks@2.0.3 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
   npm WARN @testing-library/react-hooks@2.0.3 requires a peer of react-test-renderer@>=16.9.0 but none is installed. You must install peer dependencies yourself.

   + react@16.8.6
   + react-test-renderer@16.8.6
   + @testing-library/react-hooks@2.0.3
   added 16 packages from 32 contributors and audited 36 packages in 4.588s
   found 0 vulnerabilities
   ```

Happy to accept PRs to improve this further.
