### ISSUE TITLE
Missing typing for cleanup

### ISSUE THREAD

**Issue by Quadriphobs1** [testing-library/react-hooks-testing-library#205]
- `react-hooks-testing-library` ^3:
- `react-test-renderer` version:
- `react` ^16.9:
- `node` ^11:

### What you did:

Trying to implement cleanup manually in a typescript project but the types definition `@types/testing-library__react-hooks` doesn't include the cleanup in the exported types.

### Suggested solution:

Include typings in the package internally and aviod the use of DefinitelyTyped by that the package would be having an update typings and there will be no need to update on DefinitelyTyped everytime the API changes

**Comment by mpeyper** [comment]
Hi @Quadriphobs1,

Moving the types to `DefinitelyTyped` was [a deliberate decision](https://github.com/testing-library/react-hooks-testing-library/issues/110#issuecomment-536055643) to alleviate issues we were having with type dependencies for our peer dependencies and to allow the typescript community take a more active role in maintaining the types themselves (I am not a typescript user myself) and not have to actively maintain them ourselves.

Please raise an issue in the `DefinitelyTyped` repo and consider contributing the types yourself. I'm happy to review a PR over there to add them.
