### ISSUE TITLE
Cannot access state data with react hook testing

### ISSUE THREAD

**Issue by psyycker** [testing-library/react-hooks-testing-library#255]
### What is your question:

I have a functional component using useState to update a variable called `templates`.
To update this variable, I'm doing an API call. So this call is mocked with success with jest.
I'm also targeting this change with a useEffect and `templates` has the right value.
But on my test side, the value stays undefined.

```
test('Fetch templates', async () => {

  const { result, waitForNextUpdate } = renderHook(() =>
    AddNewChainDialog({
      projectId: 'ID',
      title: 'title',
      closeCallback: () => {}
    })
  );

  await waitForNextUpdate();
  console.log(result.current.templates);
});
```

Even states which are not changing are undefined.
I'm using the version 16.9.0 of React/React-DOM/react-test-renderer and version 3.2.1 of testing library for react hooks.

Thank you for your help!

**Comment by mpeyper** [comment]
Can you please share the hook itself and a mock setup code Soni can try to replicate the scenario?

**Comment by psyycker** [comment]
`

export default function TemplateChains(): React.ReactElement {
  const [chains, setChains] = useState<ProjectChainsObject>();
  const [busy, setBusy] = useState(false);
  const [failed, setFailed] = useState(false);

  function queryChains() {
    if (busy || failed) {
      return;
    }
    setBusy(true);
    TemplateChainService.queryChains($stateParams.projectid)
      .then(response => {
        setBusy(false);
        if (response) {
          setChains(response);
        } else {
          const newChain = {
            id: null,
            projectId: $stateParams.projectid,
            projectTemplateChains: []
          };
          TemplateChainService.createChainContainer(newChain).then(
            response2 => {
              setChains(response2);
            }
          );
        }
      })
      .catch(error => {
        setBusy(false);
        $mdToast.show(
          $mdToast
            .simple()
            .textContent('Cannot get list of chains')
            .theme('error-toast')
            .hideDelay(3000)
        );
        setFailed(true);
        console.error(error);
      });
  }

  useEffect(() => {
    if (chains == null) {
      queryChains();
    }
  }, [chains]);


  return (
    <div className="TemplateChainsContainer">
      
    </div>
  );
}
`
This is the component itself. It has been simplified, so don't worry if some things are missing.

`

jest.mock(
  '../../../../../../core/services/template-chain-service/TemplateChainService',
  (): * => ({
    queryChains: (): * =>
      new Promise(resolve => {
        resolve({
          id: 'id',
          projectId: 'id',
          versionId: 'id',
          lastUpdated: 4362879,
          projectTemplateChains: [
            {
              id: '1',
              projectTemplateChainSetId: '13',
              name: 'chain 1',
              versionId: 537498,
              lastUpdated: 53534,
              projectTemplateChainNodes: [
                {
                  projectTemplateChainId: '543',
                  envelopeTemplateId: '54537890',
                  envelopeTemplateName: 'template 1',
                  nuOrder: 0,
                  versionId: 543543,
                  lastUpdated: 5432
                }
              ]
            }
          ]
        });
      })
  })
);

test('test setChains state', async () => {
  const { result, waitForNextUpdate } = renderHook(() => TemplateChains());
  await waitForNextUpdate();
  console.log(result.current.busy); // Displayed undefined
});

`

This is the test.

When the setBusy triggers, it supposed to log busy which is either true or false but logs undefined

**Comment by mpeyper** [comment]
I haven't dug in too deep yet, but on the surface, the hook you've shown returns a react component not an object with a `busy` property.

`result.current` represents the result of the function call. There is no functionality for query the internal hook state if you don't return it yourself.

Given your returning a component, it might be easier to use `@testing-library/react` and render the component for testing instead?

**Comment by psyycker** [comment]
What I've shared is the whole react functional component. But what I'm testing in it is the value of busy which changes inside the component internal state. So everything should be fine no ?

**Comment by mpeyper** [comment]
In that case, it definitely feels like you're using the wrong library. `@testing-library/react` is what you're after, which will allow you to render the component and test the output based on the components current state.  

Testing the `busy` value directly is testing an implementation detail of the component, and not something we encourage in the testing library packages.  Testing the output of a component using the components API and interactions from the "user" or the system will lead you to a more robust test that is resilient to inconsequential changes.

Now, if you feel like the logic is complex enough to extract a `useChains`, `useApi` or `useWhatever` generic variation of the logic into [a custom hook](https://reactjs.org/docs/hooks-custom.html#extracting-a-custom-hook), that's when you might have need for this library.

**Comment by psyycker** [comment]
So for you, the problem is my testing subject ? I shouldn't test that and
more test the user interactions ?

**Comment by mpeyper** [comment]
First and foremost, it's that this library is not intended to test components, but rather custom hook functions. Trying to test a component is not going to be easy and there are better tools for the job (`@testing-library/react`).

The point about implementation details is more philosophical on how you go about testing your code. [@kentcdodds explains it better than I can](https://kentcdodds.com/blog/testing-implementation-details) but the gist is that you don't want your test to break because you refactor the internals of your test subject (the component).

Another factor to consider here is that the hook state (`busy`) is kept internally to react and there is no way (that I'm aware of) to query for it to actually assert against, so even if you decide they you want to push on down this path, there are going to be some non-trivial hurdles for you along the way.

I hope this helps.

**Comment by psyycker** [comment]
It does a lot, thank you for you time !
