### ISSUE TITLE
useState is never called after calling hook function

### ISSUE THREAD

**Issue by MeisterTea** [testing-library/react-hooks-testing-library#261]
- `react-hooks-testing-library` version:3.2.1
- `react-test-renderer` version:16.10.2
- `react` version:16.10.2
- `node` version:12.10.0
- `npm` (or `yarn`) version:1.21.1

### Relevant code or config:

```js
import { act, renderHook } from '@testing-library/react-hooks'
import { useForm } from 'hooks'

  it('changes values on OnCustomchange', async () => {
    const { result } = renderHook(() => useForm({
      initialValues: {
        firstname: 'firstname'
      }
    }))

    const {
      values,
      onCustomChange
    } = result.current

    act(() => onCustomChange('firstname', 'newFirstname'))

    expect(values.firstname).toBe('newFirstname')
  })
```

useForm.js
```js
import { useState } from 'react'

const useForm = ({
  initialValues
}) => {
  const [values, setValues] = useState(initialValues)

  const onCustomChange = (name, value) => {
    setValues({
      ...values,
      [name]: value
    })
  }

  return {
    onCustomChange,
    values
  }
}

export default useForm
```

I tried using `waitForNextUpdate` after `act()` but it just hangs and fails after 5000ms

**Comment by mpeyper** [comment]
You cannot destructure `result.current` and get updates to `values`. Extracting the variable locks it into its initial value.

Just use `result.current.values` directly in your assertion and it should work. The same is true for `onCustomChange`, but you don't use it after the update so it's fine for this simple case.

**Comment by MeisterTea** [comment]
Oh my, spot on! I will try tomorrow and close the issue if everything works. Thank you!
