### ISSUE TITLE
 ReferenceError: beginWork$1 is not defined

### ISSUE THREAD

**Issue by weyert** [testing-library/react-hooks-testing-library#265]
- `react-hooks-testing-library` version: 3.2.0
- `react-test-renderer` version: 16.9.1
- `react` version: 16.12.0
- `node` version: 12.14.0
- `yarn` version: 1.21.1

### Relevant code or config:

```js
/* eslint-disable jest/valid-expect */
import {renderHook} from '@testing-library/react-hooks'
import {useUniqueId} from '../hooks'

describe('useUniqueId', () => {
  it('initially return a unique identifier', () => {
    const hook = renderHook(() => useUniqueId())
  })
})

```

### What you did:

I am trying to write a unit test but when I am running jest I am an error instead of it running the test.

I am using @kentcdodds 's `kdc-scripts` together with TypeScript and using `babel-jest`-transformer to ensure the TypeScript gets transformed for Jest.

### What happened:

When I am running the test I am getting the following error:

```
 FAIL  src/utilities/__tests__/useUniqueId.test.js
  ● Test suite failed to run

    ReferenceError: beginWork$1 is not defined

      1 | /* eslint-disable jest/valid-expect */
    > 2 | import {renderHook} from '@testing-library/react-hooks'
        | ^
      3 | import {useUniqueId} from '../hooks'
      4 | 
      5 | describe('useUniqueId', () => {

      at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15804:18
      at Object.<anonymous> (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15:3)
      at Object.<anonymous> (node_modules/react-test-renderer/index.js:6:20)
      at Object.<anonymous> (node_modules/@testing-library/react-hooks/lib/pure.js:28:26)
      at Object.<anonymous> (node_modules/@testing-library/react-hooks/lib/index.js:13:13)
      at Object.<anonymous> (src/utilities/__tests__/useUniqueId.test.js:2:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
```

### Reproduction:

Working on it, hopefully somehow had the same problem already and knows what it could be while I am working on a reproducible case.

### Problem description:

The library is unable to find a method in the `react-test-renderer`-module but I am not sure why.

**Comment by mpeyper** [comment]
It's likely because the version of `react-test-renderer` does not match the version of `react`. See the [peer dependency instructions in the docs](https://react-hooks-testing-library.com/#peer-dependencies) for details.

Let me know if the issue remains after the upgrade.

**Comment by weyert** [comment]
Yes, I have the same versions based on the `package.json`-files of the `react`, `react-dom` and `react-test-renderer` directories in `node_modules`.

**Comment by weyert** [comment]
I have been able to make a simple project which shows this problem, you can find it here:  https://github.com/weyert/testing-library-hooks-problem

You should be able to get it running via:
```
yarn install
yarn run test
```

The above error in jest should then be shown when the useUniqueId-test is running

**Comment by mpeyper** [comment]
Ok, this one was quite tricky to work out, but I think I got it...

It appears as though the `jest.config.js` override you are providing to add Typescript support is a bit aggressing when overriding the `transformIgnorePatterns` and it's removing the pattern that ignores transforms in `node_modules` for regular `js` and `jsx` files from the [base config](https://github.com/kentcdodds/kcd-scripts/blob/master/src/config/jest.config.js#L26).

Changing [this line](https://github.com/weyert/testing-library-hooks-problem/blob/master/jest.config.js#L11) to:

```js
  transformIgnorePatterns: [
    ...jest.transformIgnorePatterns,
    '[/\\\\]node_modules[/\\\\].+\\.(ts|tsx)$'
  ],
```

lets the test pass.  Please let me know if that works 😄

**Comment by weyert** [comment]
Wow amazing!

**Comment by mpeyper** [comment]
Great.  I'll consider this closed now then.

**Comment by weyert** [comment]
Working, thank you very much, @mpeyper  💃
