### ISSUE TITLE
Call to function that changes hook state not wrapped in `act()` in documentation example

### ISSUE THREAD

**Issue by aryyya** [testing-library/react-hooks-testing-library#283]
In the ["Advanced Hooks" documentation page, the Async section](https://github.com/testing-library/react-hooks-testing-library/blob/master/docs/usage/advanced-hooks.md#async) includes an example with a call `result.current.incrementAsync()` that is not wrapped in `act()` like all the other examples on the page are:

```js
import { renderHook } from '@testing-library/react-hooks'
import { useCounter } from './counter'

test('should increment counter after delay', async () => {
  const { result, waitForNextUpdate } = renderHook(() => useCounter())

  result.current.incrementAsync() // not wrapped in act()

  await waitForNextUpdate()

  expect(result.current.count).toBe(1)
})
```

If this example code is correct and the call is **not** supposed to be wrapped in `act()`, could there be an explanation as to why it differs from the synchronous examples?

**Comment by mpeyper** [comment]
The example is correct. The update does not occur when the call is made, but asynchronously when the `await waitForNextUpdate()` is waiting. The async utils automatically wrap the waiting code in the asynchronous `act` wrapper so you don't need to.

I'm on vacation at the moment, but happy to review a PR modifying the docs to make this more clear.

For what it's worth, it shouldn't hurt to wrap the call in `act` as well, if you prefer a more uniform approach in you tests.

**Comment by aryyya** [comment]
Thanks for the explanation! I created pull request #284 with the information that you gave me.
