### ISSUE TITLE
Favicon for docs

### ISSUE THREAD

**Issue by nainardev** [testing-library/react-hooks-testing-library#330]

**Comment by mpeyper** [comment]
Did you mean to post something here? I'll close it for now, feel free to update the description of there was something you wanted to raise.

**Comment by nainardev** [comment]
Set a favicon for docs, improves discoverability in Google search

**Comment by mpeyper** [comment]
Ok, I'll take it under advisement. Feel free to create a pull request adding one.

**Comment by nainardev** [comment]
You maintainers have ideas for favicon so you could create one

**Comment by mpeyper** [comment]
It appears we already have one...

![image](https://user-images.githubusercontent.com/23029903/79941729-49750780-84a8-11ea-8125-2043e35c1a5a.png)

[Docz config](https://github.com/testing-library/react-hooks-testing-library/blob/master/doczrc.js#L9)

[The image](https://github.com/testing-library/react-hooks-testing-library/blob/master/other/ram.png)

Not sure what you're saying is missing here?

Closing for now unless you can provide a clear explanation of what you want me to do.

**Comment by nainardev** [comment]
Weird. Looks like browser issue. Bye 👋
