### ISSUE TITLE
renderHook result.current is null after successfully rendering

### ISSUE THREAD

**Issue by dagda1** [testing-library/react-hooks-testing-library#390]
-->

- `react-hooks-testing-library` 3.3.0:
- `react-test-renderer` version: 16.13.1
- `react` version: 16.13.1
- `node` version:
- `npm` (or `yarn`) version:

### Relevant code or config:

```js
describe("useStepper", () => {
  it("should have an initial currentStep", async () => {
    history.push(Urls.Home);

    const { result } = renderHook(() => useStepper(), {
      wrapper: () => <Application />
    });

    await act(async () => {
      history.push(Urls.About);
    });

    expect(result.current).not.toBeNull();
  });
});
```

### What you did:

testing a custom hook that successfully completes 1 render cycle in the test

### What happened:

`result.current` is null but should contain the return value.

### Reproduction:

[codesandbox](https://codesandbox.io/s/react-ts-unit-test-example-pzlrh) that illustrates the problem

### Problem description:

`result.current` is null but should contain the return value.

**Comment by mpeyper** [comment]
Your wrapper is not rendering `children` in any way, so the hook callback (first argument of `renderHook` is never getting called.

The purpose of `wrapper` is to add the context providers (or other components that wrap the context providers, e.g. `Router`) that your hook requires, not to render complex component trees.

If you want to test this in context of your `Application`, then I suggest you use regular old `@testing-library/react` and test the hook through the components that use it.
