### ISSUE TITLE
Adjust how arguments to rendered hooks are provided

### ISSUE THREAD

**Issue by cincospenguinos** [testing-library/react-hooks-testing-library#407]
### Describe the feature you'd like:

I find usage of this library hard to grok. If I understand correctly, the current interface for rendering and rerendering a hook is something to this effect:

```jsx
const { rerender } = renderHook((props) => useMyHook(props.arg1, props.arg2), { initialProps: { arg1: 'foo', arg2: 'bar' } });
rerender({ arg1: 'bar', arg2: 'foo' });
```

A downside to this is that as arguments grow, so too does the initial props object grow too.

### Suggested implementation:

Another way to interact with rendering a hook would simply be switching over to an array of arguments. This would
allow handing the hook to render directly rather than providing an anonymous function:

```jsx
const { rerender } = renderHook(useMyHook, ['foo', 'bar']);
rerender(['bar', 'foo']);
```

### Describe alternatives you've considered:

I have no real alternatives--I just found myself struggling to get `renderHook` to work simply because I found the usage API to be unintuitive. I think my proposed solution would simplify interaction with the library, as hooks will always be functions and you will always provide arguments to a function, making an array a more expressive representation of function arguments than a javascript object.

### NOTE

I would be more than happy to implement this change to the API, given the fact that what I'm asking for is a decent amount of work.

**Comment by mpeyper** [comment]
Hi @cincospenguinos,

I've addressed similar suggestions in #56 previously.   I'll close this and move the suggestion over there to keep it all together and address talk to the idea there as well.
