### ISSUE TITLE
'not wrapped in act' warning when using waitForNextUpdate?

### ISSUE THREAD

**Issue by desktp** [testing-library/react-hooks-testing-library#434]
### What is this issue about:

I'm getting the `Warning: An update to UserProvider inside a test was not wrapped in act(...).` warning even if I'm using the `waitForNextUpdate` method to wait for the hook to update.

Wrapping the `result.current.signIn` in `act` then gives me a warning that I've called an `async` without an `await`, but then _that_ times out since that's not an async function.

Test:
```js
 it.only('should set correct error state message when account is inactive', async () => {
      jest.spyOn(Auth, 'signIn').mockResolvedValueOnce({
        ...userMock,
        challengeName: AUTH.NEW_PASSWORD_CHALLENGE,
      });

      const { result, waitForNextUpdate } = renderHook(() => useUserContext(), { wrapper });
      result.current.signIn({
        username: 'username',
        password: 'password',
        onSuccess: onSuccessMock,
      });
      await waitForNextUpdate();

      expect(result.current.error).toStrictEqual({ message: AUTH.INACTIVE_ACCOUNT_MSG, ignoreToast: true });
      expect(result.current.user).toBe(null);
      expect(onSuccessMock).toHaveBeenCalled();
    });
```

Hook snippet:
```js
const signIn = useCallback(async ({
    username,
    password,
    onSuccess,
  }) => {
    try {
      setIsLoading(true);
      const user = await Auth.signIn(username, password);

      if (user.challengeName === AUTH.NEW_PASSWORD_CHALLENGE) {
        setError({ message: AUTH.INACTIVE_ACCOUNT_MSG, ignoreToast: true });
      } else {
        setCurrentUser(user);
      }
      if (onSuccess) onSuccess();
    } catch (e) {
      setError(e)
    } finally {
      setIsLoading(false);
    }
  }, []);
```

output: 
```
|   }) => {
      41 |     try {
    > 42 |       setIsLoading(true);
         |       ^
      43 |       const user = await Auth.signIn(username, password);
      44 |       console.log('UserProvider -> user', user);
```

Am I missing something?

**Comment by mpeyper** [comment]
Sorry @desktp, I must have marked the notification for this one as done before taking a look.

The reason you're still seeing the `act` warning is that the part of the callback before the first `await` is handled synchronously in your test and the part afterwards is run asynchronously with your test meaning `setIsLoading` must be called in an `act` block before the `waitForNextUpdate` can `act` on the promise of the later updates in the callback.

The fix is pretty straight forward, update our test to wrap `result.current.signIn` in a synchronous `act` block (note: the `{ ... }` are important here) before awaiting the next update:

```js
  act(() => {
    result.current.signIn({
      username: 'username',
      password: 'password',
      onSuccess: onSuccessMock
    });
  });
  await waitForNextUpdate();
```

Let me know if this solves your issue.

**Comment by desktp** [comment]
The outer `{...}` seems to have done the trick. I had previously tried without those to no success. Any insights on what's the difference here?

**Comment by mpeyper** [comment]
`act` is a weird and wonderful beast that behaves differently if you return a `Promise` to if you return `void`.  You might have also been successful with

```js
await act(async () => result.current.signIn({
  username: 'username',
  password: 'password',
  onSuccess: onSuccessMock
});
```

but I personally think `await waitForNextUpdate()` (which is also wrapped in the `async` version of `act`) is a bit easier to read what is happening in your test.

The best link I could find for you with any sort of documentation on the different is actually [the announcement blog post about it](https://reactjs.org/blog/2019/08/08/react-v16.9.0.html#async-act-for-testing), which is also not great.

**Comment by desktp** [comment]
Indeed, documentation around it seems poor at best, even with this lib on top of it. Sometimes it feels like trial and error around different `act` behaviors and the `wait` helpers, which is not a good feeling when writing tests to maintain the application's reliability.

Thanks for the help!
