### ISSUE TITLE
Question: compatibility with @testing-library/react 

### ISSUE THREAD

**Issue by AdamSalma** [testing-library/react-hooks-testing-library#437]
Hello, 

It looks like the latest version of this library by default expects `react-testing-library` as a peer dependency, but that library is deprecated in favour of `@testing-library/react`. As such, it is not possible to use the latest versions of both libraries, unless i'm missing something.

How can we use `@testing-library/react` with this library? Are they supported? Will they be?

Thanks,
Adam

**Comment by nickmccurdy** [comment]
As far as I'm aware this doesn't require either version of React Testing Library (only `react` and `react-test-renderer` are in the [peer dependencies](https://github.com/testing-library/react-hooks-testing-library/blob/v3.4.1/package.json#L66-L69)) so you should be fine using it to test components alongside your hooks. If you have any issues with this please leave an example that reproduces it and I will reopen the issue.
