### ISSUE TITLE
Slightly garbled English in waitForValueToChange docs

### ISSUE THREAD

**Issue by ExplodingCabbage** [testing-library/react-hooks-testing-library#456]
### Problem description:

The following sentence, found at https://react-hooks-testing-library.com/reference/api#waitforvaluetochange and in api-reference.md in this repo, is ungrammatical and confusing:

> It expected that the `result` of `renderHook` to select the value for comparison.

### Suggested solution:

I'm not 100% certain what the intended meaning was, but maybe the missing words needed to make this make sense are these:

> It [is] expected that the `result` of `renderHook` [will be used] to select the value for comparison.

Or, equivalently:

> Typically, you will pass a selector that accesses the `result` returned from `renderHook` and returns some property from it.

CC @mpeyper who wrote the original prose.

**Comment by mpeyper** [comment]
You're not wrong, what's there doesn't make sense.

I'm happy with either of those suggestions if you want to submit a PR to change it.
