### ISSUE TITLE
Trigger a state change  on a dependency custom hook

### ISSUE THREAD

**Issue by MauroGL** [testing-library/react-hooks-testing-library#459]
Hi everybody, I'm really struggling with a scenario where I need to test a custom hook dependency on a component that is being updated by a socket. I'm not sharing code because I really don't think it's going to help since it's going to add a lot of noice and the scenario is pretty simple to write, let me know if you still need some code example to explain and I'll try to create a simple example.

So this is the scenario:

I have two providers with their respective custom Hooks to access the states and functions from the context.

**NotificationProvider**, _useNotification_
**ConsumerProvider**  _useConsumer_

**ConsumerProvider** gets a state from the _useNotification_ hook ( _useNotification_ is being imported)
The **notificationsList** (a state in the NotificationProvider context) is being updated by a socket inside the **NotificationProvider**

**Once the notificationList** gets updated by an incomming notification through the socket, the **ConsumerProvider** rerenders and an useEffect with a listener on the **notificationList** do some logic.

The issue:
I want to test the **useEffect** logic that runs when a socket sends a message, updates the **notificationList**, rerenders the **ConsumerProvider** and triggers the **useEffect** tied to **the notificationList** 

What I already tried
Mocking the _useNotification_ in order to change the value of the _useNotification_ hook, but it's not going to trigger a rerender, and if I call the mockedHook.rerender() the useEffect that runs initially with [] will run in parallel alongside the one listening to _useNotification_  leaving a lot of stuff not being properly loaded when the useEffect runs.

I would be eternally grateful if someone can give me an idea on how could I achieve this, if possible.

This is the code example:

```
import React, { useState, useEffect } from 'react';
import { useNotification } from 'providers/NotificationProvider';
import ConsumeContext from './ConsumeContext';
import { pushToArray } from '../utils/providerUtils';

const ConsumerProvider = ({ children }) => {
  const [listOfMessages, setListOfMessages] = useState([]);
  const { notifications } = useNotification();  / <=============  state I want to mock

  const contextValue = {
    listOfMessages,
  };

  useEffect(() => { / <=============  useEffect I want to test
    const incommingNotification = notifications[notifications.length - 1];

    const asyncBlock = async () => {
      switch (incommingNotification.action) {
        case 'new message':
          {
            const activity = await getNewMessage(
              incommingNotification,
            );

            const updated = pushToArray(listOfMessages, activity, 'id');
            if (updated) {
              setListOfMessages([...listOfMessages]);
            }
          }
          break;
        default:
          break;
      }
    };

    asyncBlock();
  }, [listOfMessages.length]);

  return React.createElement(
    ConsumeContext.Provider,
    { value: contextValue },
    children,
  );
};

export default ConsumerProvider;
```

**Comment by mpeyper** [comment]
Hi @MauroGL,

It's hard to give specific advice without seeing some code.  I would have thought you could achieve what it sounds like your describing by using mocking `useNotification` so I must be missing something.

**Comment by MauroGL** [comment]
@mpeyper ok, so, first of all, thank you for your reply. 
I added some code that reflects what I'm trying to test, basically `notifications` is a state that changes when a socket receives a new notification (in a complete different provider, the **NotificationProvider** , so it doesn't require user intervention to change.
That's what's killing my test, because I can't find a way to simulate a change on that state so I can trigger the useEffect listening to that state.

**Comment by mpeyper** [comment]
Hi MauroGL,

Sorry it has taken me so long to get back to this.  Unfortunately I'm not going to very helpful after all this waiting.

This libraries purpose is for testing custom hooks (e.g. `useNotification`), not components consuming them (e.g. `ConsumerProvider`).  That is still firmly the territory of `@testing-library/react`, so I don't have much advice for this situation.

If you wanted to extract a new custom hook, e.g. `useMessageList`, then you could potentially use this library to test that custom hook.  Something like:

```js
function useMessageList(notifications) {
  const [listOfMessages, setListOfMessages] = useState([]);

  useEffect(() => {
    const incommingNotification = notifications[notifications.length - 1];

    const asyncBlock = async () => {
      switch (incommingNotification.action) {
        case 'new message':
          {
            const activity = await getNewMessage(
              incommingNotification,
            );

            const updated = pushToArray(listOfMessages, activity, 'id');
            if (updated) {
              setListOfMessages([...listOfMessages]);
            }
          }
          break;
        default:
          break;
      }
    };

    asyncBlock();
  }, [listOfMessages.length]);

  return listOfMessages;
}

const ConsumerProvider = ({ children }) => {
  const { notifications } = useNotification();
  const listOfMessages = useMessageList(notifications);

  const contextValue = {
    listOfMessages,
  };

  return React.createElement(
    ConsumeContext.Provider,
    { value: contextValue },
    children,
  );
};
```

And then use the [`rerender` functionality](https://react-hooks-testing-library.com/reference/api#rerender) to trigger updates with new notifications.

However, I do believe that this is the sort of scenario where you want to be testing the component as a whole and not the individual hooks so I would recommend looking to the standard `@testing-library/react` for this.

I must admit though, I'm a bit confused as to how your hooks is supposed to be working.  If `updated` is falsey, then `setListOfMessages` is never called so `listOfMessages.length` will never change in the `useEffect` dependency array and it wont rerun.  However, even if `updated` was `truthy`, wont `setListOfMessages([...listOfMessages])` just set the `listOfMessages` to the same items, so `listOfMessages.length` will still be the same and the effect still wont retrigger?

Obviously I could be wrong and I don't have the context on what you're trying to build, but I think the dependency array should be `[notifications.length]` instead?
