### ISSUE TITLE
useEffect with dependencies seems to make the test not to run at all

### ISSUE THREAD

**Issue by viktorlarsson** [testing-library/react-hooks-testing-library#460]
- `react-hooks-testing-library` version: 3.4.2
- `react-test-renderer` version: 16.13.1
- `react` version: 16.13.1

### Relevant code or config:

```js

// useHook.js
export const useHook = ({ translations }) => {
  const [someStuff, setSomeStuff] = useState([]);
  const { data, ready } = translations;

  useEffect(() => {
    if (ready && data) {
      const yolo = [{ foo: "bar" }];

      setSomeStuff(yolo);
    }
  }, [ready, data]);

  return { someStuff };
};

// useHook.test.js
describe("useHook", () => {
  it("some stuff should have data", async () => {
    const { result } = renderHook(() =>
      useHook({ translations: { ready: true, data: [] } })
    );

    expect(result.current.someStuff.length).toBe(1);
  });
});
```

### Reproduction:

https://codesandbox.io/s/flamboyant-cerf-eoxi7?file=/src/useHook.test.js

![image](https://user-images.githubusercontent.com/722315/94553121-4b61a480-0258-11eb-8050-4643828953b8.png)

### Problem description:

When using useEffect, in combination with dependencies makes the test just come to a complete halt. When removing the dependancies, or by mocking setState, it works but I would like to actually be able to test current. As you can see in the code sandbox, the test isn't executed.

**Comment by mpeyper** [comment]
The `renderHook` callback was creating a new reference for `translations` each time it was called (every render) which was triggering the effect.  The body of the effect _is_ conditional, but unfortunately it was also always `true`, so `setSomeStuff` was always being called with a new `yolo` reference and falls into the infinite render loop of "effect, setState, render, effect, setState, render, etc".

I've [updated your sandbox with 2 options for working around this](https://codesandbox.io/s/ancient-thunder-y47m7?file=/src/useHook.test.js), but essentially you need to pull the props for your hook out of the callback:

```js
describe("useHook", () => {
  it("some stuff should have data", async () => {
    const { result } = renderHook((props) => useHook(props), {
      initialProps: { translations: { ready: true, data: [] } }
    });

    expect(result.current.someStuff.length).toBe(1);
  });

  it("some stuff should have data (alternative)", async () => {
    const props = { translations: { ready: true, data: [] } };
    const { result } = renderHook(() => useHook(props));

    expect(result.current.someStuff.length).toBe(1);
  });
});
```

**Comment by viktorlarsson** [comment]
That worked perfectly, thank you! Could not find anything in issue or docs about this, should this be updated somehow? I can send a PR but not sure if it should or if I am doing some unreasonable design

**Comment by mpeyper** [comment]
It's a tough one because it's a result of how hooks and JavaScript in general work with referential equality of objects rather than something we can control at the testing-library level, but you're definitely not the first to fall into this trap. To make it worse, it appeared in codesandbox to just not be running the tests, but when I copied them locally, I could see it was that the test was actually never finishing.

Perhaps we need a troubleshooting section of the docs to put these kinds of common pitfalls (there's probably a few others I can think of that come up regularly in the issues).

**Comment by viktorlarsson** [comment]
Thanks!

**Comment by antonsamper** [comment]
> The renderHook callback was creating a new reference for translations each time it was called (every render) which was triggering the effect. 

This should be better documented as its not obvious what the problem is, specially when it works in the browser.
