### ISSUE TITLE
Await Fetch in Hook

### ISSUE THREAD

**Issue by dschinkel** [testing-library/react-hooks-testing-library#465]
I don't see how you're supposed to await a fetch from your test using `renderHook` when fetch happens inside a Hook, because of Closure.  Is this even possible here?

```js
const FeaturedCompanies = () => {
  const [featuredCompanies, setData] = useState([]);

  useEffect(() => {
    const fetchCompanies = async () => {
    const companies: Array<Company> = await findFeaturedCompanies();
    setData(companies);
  };

  fetchCompanies();
}, [featuredCompanies]);
...
```

**Test contains:**
```js
const {result} = renderHook(() => FeaturedCompanies())
await Promise.resolve();
expect(....whatever)
```

Here, the **expect** is being hit before **setData** is called.  And I see no way to await that fetch from the test because of Closure.

Also is there a way to use stuff like `getByTestId` with this lib on the result when the result is DOM output?

**Comment by dschinkel** [comment]
was able to get it to work using

rerender();
await waitForNextUpdate()

however, is there a way to query the result rather than navigate through a ton of children.props combinations?  I thought this was part of react testing lib so I figured there must be some way to query the results of the DOM hear, preferably by getByTestId.

**Comment by mpeyper** [comment]
Is `FeaturedCompanies` a hook or a component?  If it's a component, just use `@testing-library/react` and `render` it.  You don't need this library.

This library is for testing custom hooks only.  DOM is not a requirement and one of the reasons we use `react-test-renderer` and not `react-dom` for rendering.  The `result.current` value is the value returned by the hook, nothing to do with components or elements or DOM, so there is nothing to query with those utilities.

If `FeaturedCompanies` is a custom hook then you'll need to share more info on what the hook is trying to achieve to get better support on how to structure your test.

FWIW, you shouldn't need the `rerender` call from what you've shown.  Just 

```js
const { result, waitForNextUpdate } = renderHook(() => FeaturedCompanies())
await waitForNextUpdate()
```

should be enough (this is assuming there isn't another state update resolving the promise before `setData` is being called).

**Comment by dschinkel** [comment]
it's a hook.  It's unfortunate we can't use this to query on DOM for hooks though.  But thanks.

**Comment by mpeyper** [comment]
But what is in the DOM that you want to query?  We call the hook, attach the result to an object then render `null`.  What is your hook returning?

(I'm actually curious)
