### ISSUE TITLE
Unpredictable behavior for Apollo MockedProvider results in act() errors or others

### ISSUE THREAD

**Issue by sajadghawami** [testing-library/react-hooks-testing-library#480]
Hey guys,

### Problem description:

I've been trying to write tests for an application that uses apollo, apollo-hooks and some custom hooks.

### Relevant code or config:

From what i understood from the [Apollo-Docs ](https://www.apollographql.com/docs/react/development-testing/testing/#testing-final-state) you need to have a:

```js
  await new Promise(resolve => setTimeout(resolve, 0)); // wait for response
```

After initializing the component (this is taken from the docs):

```js
 const component = renderer.create(
    <MockedProvider mocks={[dogMock]} addTypename={false}>
      <Dog name="Buck" />
    </MockedProvider>,
  );

  await new Promise(resolve => setTimeout(resolve, 0)); // wait for response
```

The Problem with that approach was, that i need to pass the wrapper to `renderHook` without mountig/rendering it because react-hooks-testing-library is for testing hooks. On the other hand, apollo actually needs the mounted component to work properly.
So in ended up doing the following:

```js
   const wrapper = ({ children }: any) => (
    <MockedApolloProvider mocks={mockRequest} addTypename={false}>
      {children}
    </MockedApolloProvider>
    );

  it('should hydrate the buyerCart and update the delivery dates accordingly', async () => {
    const { result } = renderHook(() => useBuyerCart(), { wrapper });

    await act(async () => {
      const { buyerCartHydrate } = result.current;
      buyerCartHydrate(); // <-- FYI: This function calls other internal functions that at some point do a redux-dispatch
    });

    // check the state
    const actions = mockStore.getActions();
    expect(actions).toMatchSnapshot();
  });

```

Which does work... sometimes, but sometimes it doesn't "wait" till everything was been properly calculated.

### What happened:

You will either get this error:

```js
  console.error
    Warning: An update to TestHook inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
```

Or, the `expect(actions).toMatchSnapshot();` do not match. Again, not always, but sometimes.

### Environment

- `react-hooks-testing-library` version: 3.4.2
- `react-test-renderer` version: 16.14.0
- `react` version: 17.0.0
- `node` version: v12.18.0
- `npm` (or `yarn`) version: 6.14.4

### Suggested solution:

So i ended up sticking the following to the end:

```js
    // we need this for not to show the act error
    waitForNextUpdate();
    // we need this to wait for all promises to resolve
    await new Promise((resolve) => setTimeout(resolve, 100));
```

Which feels horrible and somehow wrong... because i am manually setting a timer to `100`. Setting a timer to `0` does sometimes work, but sometimes it doesn't.

So in short the following questions:
- Is there a way to give the renderHook a "rendered" Wrapper? If so, how?
- Is there some more elegant way to wait
- Is there something wrong with the syntax? I ve tried everything from not `async act`, to only using `waitForNextUpdate()` and only `act` but the only solution that really worked was this:

```js
  it('should hydrate the buyerCart and update the delivery dates accordingly', async () => {
    const { result } = renderHook(() => useBuyerCart(), { wrapper });

    await act(async () => {
      const { buyerCartHydrate } = result.current;
      buyerCartHydrate(); // <-- FYI: This function calls other internal functions that at some point do a redux-dispatch
    });
    // we need this for not to show the act error
    waitForNextUpdate();
    // we need this to wait for all promises to resolve
    await new Promise((resolve) => setTimeout(resolve, 100));
    // check the state
    const actions = mockStore.getActions();
    expect(actions).toMatchSnapshot();
  });


```

Thank you very much. <3

**Comment by mpeyper** [comment]
Hi @sajadghawami,

Sorry it's taken a while to get back to you (I've been on leave).

> Is there a way to give the renderHook a "rendered" Wrapper? If so, how?

No, it must render the wrapper to ensure they are using the same react root (otherwise things like context don't work)

> Is there some more elegant way to wait

We have some async utils that can wait if different ways:

1. `waitForNextUpdate` - resolves on the hook's next render
2. `waitForValueToChange` - resolves when the selector returns a value that is different to to first call
3. `waitFor` - resolves when the callback returns truthy or `undefined` (generally used to wait for an exception to pass)

> Is there something wrong with the syntax? I ve tried everything from not `async act`, to only using `waitForNextUpdate()` and only `act` but the only solution that really worked was this:

`await act(async () => {...})` is only useful if you have a promise to `await` to tell the `act` call that it's finished.  Reading, the comment, I assume `buyerCartHydrate` just returns immediately and the dispatch to the store is what eventually "resolves" the update, but you don't have a promise to represent this, so you can probably just use a basic `act(() = {...})`.  If I'm right, then using the `waitFor` util can clean this test up a bit:
```js
  it('should hydrate the buyerCart and update the delivery dates accordingly', async () => {
    const { result, waitFor } = renderHook(() => useBuyerCart(), { wrapper });

    act(() => {
      const { buyerCartHydrate } = result.current;
      buyerCartHydrate(); // <-- FYI: This function calls other internal functions that at some point do a redux-dispatch
    });

    waitFor(() => {
      const actions = mockStore.getActions();
      expect(actions).toMatchSnapshot();
    }, { interval: 20, timeout: 100 }) // interval is only required if the dispatches don't cause the hook to rerender
  });
```

If `buyerCartHydrate` _does_ return a promise that resolves when all the updates have settled, then you should just need to whack am `await` in front of it and remove the `waitForNextUpdate`, etc.  before your expectations.

```js
  it('should hydrate the buyerCart and update the delivery dates accordingly', async () => {
    const { result } = renderHook(() => useBuyerCart(), { wrapper });

    await act(async () => {
      const { buyerCartHydrate } = result.current;
      await buyerCartHydrate();
    });

    const actions = mockStore.getActions();
    expect(actions).toMatchSnapshot();
  });
```

Hope this helps.
