### ISSUE TITLE
waitFor times out waiting for Jest spy to be called

### ISSUE THREAD

**Issue by michaelhankin** [testing-library/react-hooks-testing-library#486]
Hi, I'm writing a test that validates that my custom hook logs an error when fetch returns an error status code. I've created a spy on `console.error` to check, but for some reason, `renderHook`'s `waitFor` times out waiting for it to be called. 

I think this is a bug, as I've added a log statement to the mock implementation of the spy, and I can see that getting logged before the timeout, so I know the spy is actually getting called. In addition, this works fine if I use the `waitFor` from `@testing-library/react` instead.

See the snippet below for a reproduction.

### Package versions:

- `react-hooks-testing-library` version: 3.4.2
- `react-test-renderer` version: 16.12.0
- `react` version: 16.13.1
- `node` version: 12.18.4
- `npm` version: 6.14.6

### Reproduction:

```js
// useAsyncHook.js
const useAsyncHook = (val) => {
  const fetchData = async () => {
    const res = await fetch(/* ... */)
    if (!res.ok) {
      console.error(/* ... */)
      return
    }
    // ...
  }

  useEffect(() => fetchData(), [])
  // ...
}

// useAsyncHook.test.js
it('logs on error', async () => {
  // Mock fetch to return 500
  // ...
  const consoleErrorSpy = jest.spyOn(console, 'error').mockImplementationOnce(() => {
    console.log('calling') // Gets logged before timeout
  })
  const { waitFor } = renderHook(() => useAsyncHook('foo'))
  await waitFor(() => expect(consoleErrorSpy).toBeCalledTimes(1)) // Times out
  // ...
}
```

### Error:
```
Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error
```

**Comment by mpeyper** [comment]
Hi @michaelhankin,

Try adding an interval on the `waitFor` call:

```js
await waitFor(() => expect(consoleErrorSpy).toBeCalledTimes(1), { interval: 100 })
```

The default behaviour is to only test when the  hook triggers a rerender via a state update. Checking on an interval is likely to become the default behaviour in the next major version.

**Comment by michaelhankin** [comment]
@mpeyper got it, that worked. Thanks a lot!

**Comment by wellchrys** [comment]
@mpeyper Thanks! This also worked for me :)
