### ISSUE TITLE
Migrate CI to GitHub Actions

### ISSUE THREAD

**Issue by mpeyper** [testing-library/react-hooks-testing-library#499]
### Describe the feature you'd like:

The queue times on travis-ci are just getting stupidly long at this point and I gave GitHub Actions a go in a personal project recently and it was really nice. I'd like to convert this project over to using it instead.

### Suggested implementation:

Read the docs, implement the config.

### Describe alternatives you've considered:

There's plenty of other CIs out there, but I don't see any reason to consider other alternatives at this stage. Happy to hear suggestions though.

### Teachability, Documentation, Adoption, Migration Strategy:

N/A

**Comment by nickmccurdy** [comment]
`yo kcd-scripts` would make this easier, though you'd have to change some of the scripts unless you also plan on migrating to `kcd-scripts` (see #498).
