### ISSUE TITLE
Implement automatic releases

### ISSUE THREAD

**Issue by mpeyper** [testing-library/react-hooks-testing-library#501]
### Describe the feature you'd like:

I'm barely finding time to respond to issues and review PRs these days, so often releases are only occuring a few days after they hit master. I'd love to have released go out automatically on successfully master builds.

### Suggested implementation:

Semantic Release is the obvious choice here. Many @testing-library packages are already using it so we should have a pretty good template to follow.

Might be worth combining with or waiting for #499.

I haven't used semantic release before so any assistance is welcome.

### Describe alternatives you've considered:

N/A

### Teachability, Documentation, Adoption, Migration Strategy:

N/A

**Comment by marcosvega91** [comment]
I have seen that you have released a version manually. `semantic-release` will release a new version when the PR merged is of kind `feat` or `fix`. I could suggest you to use `Squash and Merge` in most cases so you can update the merge commit following the conventions.

**Comment by mpeyper** [comment]
@marcosvega91, yeah, I tried to squash and merge and PR but I didn't realise there was a seperate field for the main commit message to the description and so [I messed it up](https://github.com/testing-library/react-hooks-testing-library/commit/c3e09ed7456dc2fb15fb1aff31bf352eb3e2a569) and semantic-release obviously just ignored it.
