### ISSUE TITLE
waitFor times out

### ISSUE THREAD

**Issue by yordis** [testing-library/react-hooks-testing-library#517]
```json
{
    "@testing-library/react": "11.2.2",
    "@testing-library/react-hooks": "3.4.2",
    "react": "17.0.0",
    "react-dom": "17.0.0",
    "react-query": "2.26.3",
    "react-scripts": "3.4.3",
    "react-test-renderer": "17.0.1"
}
```

### Relevant code or config:

Codesanbox: https://codesandbox.io/s/react-query-redirect-7tzct

```tsx
// hook.ts
import { useQuery } from 'react-query';
import { useHistory } from 'react-router-dom';

export function useMyHook() {
  const history = useHistory();
  const query = useQuery({
    config: {
      onError() {
        history.push('/accounts');
      },
    },
    queryKey: ['something'],
    queryFn() {
      return Promise.reject(new Error('hello'));
    },
  });

  return {
    query,
  };
}
```

```tsx
// hook.test.tsx
import { renderHookWithWrapper } from './renderer';
import { useMyHook } from './hook';

describe('useMyHook', () => {
  test('redirects the page', async () => {
    const { result, waitFor, history } = renderHookWithWrapper(
      () => useMyHook(),
      {
        config: {
          initialEntries: ['/accounts/no-found-id'],
        },
      }
    );

    await waitFor(() => result.current.query.isError);
    expect(history.location.pathname).toBe('/accounts');
  });
});
```

### What you did:

Codesanbox: https://codesandbox.io/s/react-query-redirect-7tzct

### What happened:

It times out

### Reproduction:

Codesanbox: https://codesandbox.io/s/react-query-redirect-7tzct

### Problem description:

Debugging the situation, I see an infinite loop in the Promise microtask handling, it goes down to few promises and then jumps back to a higher value, never getting to zero promise resolved.

My hypothesis is that the generator keeps registering Promise microtasks.

### Suggested solution:

🤷🏻 

### Extra

- I tried #486 didn't work

**Comment by joshuaellis** [comment]
Can I ask, how come you're not creating a mock fetch function like [here](https://react-query.tanstack.com/docs/guides/testing#testing-network-calls)?

**Comment by joshuaellis** [comment]
Hi @yordis you've closed the issue, did you manage to solve it?

**Comment by yordis** [comment]
@joshuaellis false promise, it was actually `history.push` (using `history` pkg and react router) in my code, for some reason, causing a timeout.

**Comment by yordis** [comment]
I actually will reopen this, because it is not clear to me that it is `history` object causing the actual underline issue.

**Comment by yordis** [comment]
My problem was setting up the routes (check the codesandbox) in https://codesandbox.io/s/react-query-redirect-7tzct?file=/src/renderer.tsx 

My Router wrapper didn't define a fallback so my routing got into an infinite loop

```tsx
// this is wrong
RouterWrapper(props: any) {
      return (
        <Router history={history}>
          {args?.path ? (
            <Route path={args.path}>{props.children}</Route>
          ) : (
            props.children
          )}
        </Router>
      );
    }

// this is the fix, notice the Switch and the extra routing
RouterWrapper(props: any) {
      return (
        <Router history={history}>
          <Switch>
            {args?.path && <Route path={args.path}>{props.children}</Route>}
            <Route path="*">{props.children}</Route>
          </Switch>
        </Router>
      );
    }
```

**Comment by joshuaellis** [comment]
Thansk for sharing, I think it's important to share our fixes even if it wasn't the library's fault, just incase someone is experiencing a similar problem!
