### ISSUE TITLE
react-test-renderer `update` method does not rerender component with new props 

### ISSUE THREAD

**Issue by joshuaellis** [testing-library/react-hooks-testing-library#530]
- `react-hooks-testing-library` version: 4.0.0
- `react-test-renderer` version: 17.0.1
- `react` version: 17.0.1
- `node` version: 14.0.0
- `npm` (or `yarn`) version: 1.22.5 (yarn)

### Reproduction:

https://github.com/joshuaellis/react-test-renderer-update-issue

### Problem description:

`@testing-library/react-hooks` rerender function uses `react-test-renderer` `update` under the hood. The props are correctly passed to `update` function but the hook does not re-render with the new props so the test fails.

<img width="522" alt="image" src="https://user-images.githubusercontent.com/37798644/104036363-39828c80-51cb-11eb-9d73-48f0680f4e05.png">

### Suggested solution:

I think this has something to do with `react-test-renderer` so i've raised it with them [here](https://github.com/facebook/react/issues/20561) but also want to keep an eye on it.

## The expected behavior

the last two logs (in the image above) should say: 
"using func func2"
"im func 2"

**Comment by joshuaellis** [comment]
may be related to #525

**Comment by joshuaellis** [comment]
Okay, after recreating it all in `react-test-renderer` not using RHTL, it passes. This is the branch with the code & passing test, must be something wrong with our async utils I suppose.... Or maybe I fluked the branch – https://github.com/joshuaellis/react-test-renderer-update-issue/tree/only-use-test-renderer

**Comment by mpeyper** [comment]
Try making it

```js
const { result, rerender } = renderHook(({ func }) =>
      usePolling({
        func,
        interval: 1000
      }),
      {
        initialProps: {
          func: func1
        }
      }
    )
```

**Comment by joshuaellis** [comment]
Ah stupid me. Although I am going to ask, out of my own curiousity, why do we have to do it this way? It seems in my opinion a little counter intuitive. Because if I want to add a new prop down the line that wasn't defined in the original render, it passes through correctly. Hence why I was confused.

Do you think we could/should remove it?

**Comment by joshuaellis** [comment]
Doesn't matter, i've had a deep look, it all makes sense, I now have an even further understanding of the engine we're using 🧠 I just realised the `rtl` way I built even uses that pattern! 🤕

**Comment by mpeyper** [comment]
If you're interested, #56 is mostly about how much I hate how we deal with changing props.

**Comment by joshuaellis** [comment]
I'll take a look, i've been trying to make my way through the issues we've got open and understand them properly 👍🏼
