### ISSUE TITLE
[docs] Make links work on both documentation Github and websites

### ISSUE THREAD

**Issue by sakito21** [testing-library/react-hooks-testing-library#552]
Currently the link is not available in the Github docs.
Find and implement a way that works for both.

> It's an annoying thing at the moment where the links work for the site or for GitHub, but not both. If anyone has an bright ideas on how to make it work for both, I'll gladly review a PR for it.

https://github.com/testing-library/react-hooks-testing-library/pull/550

**Comment by mpeyper** [comment]
I'm going to close this for now, but if anybody wants to pick this up I'm happy to reopen it (I'm assuming you aren't actually working on anymore @sakito21?).
