### ISSUE TITLE
problem with state and useFocusEffect of navigation

### ISSUE THREAD

**Issue by misaku** [testing-library/react-hooks-testing-library#565]
I use react navigation and in my code i need to use `useFocusEffect`  because i need to do useEffect one screen active,
i try to mock but if i mocked useFocusEffect execute only one time.
so i found one solution:
```JS
const wrapper: React.FC<any> = ({children, ...props}) => {
    const Stack = createStackNavigator();
    return (
      <NavigationContainer>
        <Stack.Navigator>
          <Stack.Screen
            name="testecollector"
            component={() => <ScanPackagesCollectorProvider {...props}>{children}</ScanPackagesCollectorProvider>}
          />
        </Stack.Navigator>
      </NavigationContainer>
    );
  };
```
but now i have other problem, one problem is in my caode in provider i pass list and setList, i wouldlike update this state,
the seconde problem state of context change but dont return in hook on test.
```JS
onst {
      result: {current},
      rerender,
      waitFor,
    } = renderHook(() => useScanPackagesCollector(), {
      wrapper,
      initialProps: {
        list: [{id: 1, name: 'teste', checked: false}],//i try to pass real state and setState but not work
        setList: mockSetList,
        loading: mockIsLoading,
        name: 'collector',
        conditionFindItemInList: (itemB) => {
          return (item: {id: any}) => {
            return item.id === itemB.id;
          };
        },
        msgLoading: mockMSGLoading,
        toDo: mockToDo,
        typeScan: 'QR_CODE',
        validator: mockValidator,
        renderItem: mockRenderItem,
        keyExtractor: (item) => item.id,
        msg: 'test',
        partial: false,
        hasAvatar: true,
      },
    });
    act(() => {
      current.setFilter(2);
    });
    act(() => {
      current.setFilter(1);
    });
    await waitFor(() => expect(mockSetList).toHaveBeenCalled());
```

**Comment by joshuaellis** [comment]
hi @misaku, 

This seems like a complicated example, it'd be great if you could provide a small reproducable example for us to play with. In the mean time, don't destructure `result` into `{ current }`. You should call it like so:

```js
act(() => {
  result.current.setFilter(2)
})
```

this might not solve your issues, but it'll be an issue when you're asserting from the result.

**Comment by misaku** [comment]
hi change to result.current and i refactory my code and found the problem. i need to put one conditional before setState and i neet to chance usefocuseffect to useEfect with isFocused. thanks for helpme
