### ISSUE TITLE
extract the `react-test-renderer` logic from this library

### ISSUE THREAD

**Issue by ianstormtaylor** [testing-library/react-hooks-testing-library#566]
### Describe the feature you'd like:

This library is great for testing hooks, since it doesn't use `dom-testing-library` under the covers, which is slow. But if you need to render a component you have to use `react-testing-library` which brings in all of `jsdom`.

I think the internal component-based (not hook-based) rendering logic in this library would be really useful as a standalone package (or exported from this one).

This would be especially useful for testing hooks that rely on `useContext`, where you want to verify behaviors across a component tree, but can't use this library since it's only for rendering a single hook, and don't want to use `react-testing-library` because it is much slower.

### Suggested implementation:

I think it would be useful to have a package called `react-native-testing-library` which uses the `react-test-renderer` under the covers, and is very similar to what this package exports from `./src/native/pure.ts`. With that change, `asyncUtils` would be moved into the new package (and re-used in this one), so that you can use them in either.

This would essentially create a simple alternative to `react-testing-library` that doesn't require the use of the DOM. But still with the niceness that `react-test-renderer` doesn't provide out of the box.

### Describe alternatives you've considered:

It could also be refactored to be exported from this library instead. This would be the simpler approach that can be taken first to validate the idea.

**Comment by mpeyper** [comment]
Are you looking for this package? https://github.com/callstack/react-native-testing-library

**Comment by ianstormtaylor** [comment]
@mpeyper Umm, wow, yes I believe I am 😄
