### ISSUE TITLE
Message event listener not firing as expected when testing custom hook

### ISSUE THREAD

**Issue by kimyu92** [testing-library/react-hooks-testing-library#567]
### Message event listener not firing as expected
I had a hard time to test state for a custom hook that wrap message listener due to event not firing at all. Would it even be possible without exposing `messageHandler` simply for testing purpose:

```jsx
// eg. usePostMessageEffect.js
const usePostMessageEffect = () => {
  const [isReceived, setIsReceived] = useState(false);

  useEffect(() => {
    const messageHandler = (event) => {
      setIsReceived(true);
    };

    window.addEventListener('message', messageHandler, false);

    return () => {
      window.removeEventListener('message', messageHandler, false);
    };
  }, []);

  return isReceived;
}
```

```jsx
// eg. usePostMessageEffect.spec.js
describe('usePostMessageEffect', () => {
  jest.spyOn(window, 'addEventListener');
  jest.spyOn(window, 'removeEventListener');

  it('should have received', () => {
    const { result } = renderHook(() => usePostMessageEffect());

    act(() => {
      const messageEvent = new MessageEvent();
      // Not firing the event
      fireEvent(window, messageEvent);
    });

    // Failed the expectation
    expect(result.current).toEqual(true);
  });
});
```

**Comment by joshuaellis** [comment]
Did you know you called your function `messageListener` in the `useEffect` hook but you're calling it using `messageHandler`?

**Comment by joshuaellis** [comment]
Anyway, beside this i've managed to create a test for you that passes, which can be seen here: https://codesandbox.io/s/cocky-cannon-ecgzi?file=/src/component.test.js

so why is this here?
```js
await new Promise((resolve) => setTimeout(resolve, 100));
```

Well, this is here because of this [comment](https://github.com/jsdom/jsdom/issues/2245#issuecomment-392556153). This all comes down to how `window.postMessage` is handled in JSDom. I know you used fireEvent, but imo no need in this case and from memory they use `jest.useRealTimers` which has some issues in codesandbox.... If you find this still doesn't work with `fireEvent` can you make a github example for me to use please?

**Comment by kimyu92** [comment]
> Did you know you called your function `messageListener` in the `useEffect` hook but you're calling it using `messageHandler`?

Sorry for the typo 😅 



> Anyway, beside this i've managed to create a test for you that passes, which can be seen here: https://codesandbox.io/s/cocky-cannon-ecgzi?file=/src/component.test.js
> 
> so why is this here?
> 
> ```js
> await new Promise((resolve) => setTimeout(resolve, 100));
> ```
> 
> Well, this is here because of this [comment](https://github.com/jsdom/jsdom/issues/2245#issuecomment-392556153). This all comes down to how `window.postMessage` is handled in JSDom. I know you used fireEvent, but imo no need in this case and from memory they use `jest.useRealTimers` which has some issues in codesandbox.... If you find this still doesn't work with `fireEvent` can you make a github example for me to use please?

Thanks you! The example of adding a small timeout indeed resolves the issue.
