### ISSUE TITLE
renderHook is not a function

### ISSUE THREAD

**Issue by SeungsuKim** [testing-library/react-hooks-testing-library#575]
- `react-hooks-testing-library` version: "^5.1.0"
- `react` version: "^17.0.1"
- `react-dom` version (if applicable): "^17.0.1"
- `node` version: "14.15.1"
- `yarn` version: "1.22.10"

### Relevant code or config:

```js
import { MockedProvider } from '@apollo/client/testing';
import { generateCache } from '@test';
import { renderHook } from '@testing-library/react-hooks/dom';
import React from 'react';

import useMessage from './useMessage';

describe('useMessage', () => {
  describe('sendMessage', () => {
    const cache = generateCache();
    const wrapper = ({ children }: { children: React.ReactElement }) => (
      <MockedProvider mocks={[]} cache={cache}>
        {children}
      </MockedProvider>
    );
    const { result } = renderHook(() => useMessage({ chatId: 'chat-id' }), {
      wrapper,
    });

    it('can be initialized', () => {
      expect(result.current.operations.sendMessage).toBeTruthy();
    });
  });
});
```

### What you did:

Tried to use `renderHook` function by using `react-dom`

### What happened:

```
TypeError: (0 , _dom.renderHook) is not a function

      14 |       </MockedProvider>
      15 |     );
    > 16 |     const { result } = renderHook(() => useMessage({ chatId: 'chat-id' }), {
         |                        ^
      17 |       wrapper,
      18 |     });
      19 |

      at src/hooks/useMessage/useMessage.test.tsx:16:24
      at src/hooks/useMessage/useMessage.test.tsx:9:3
      at Object.<anonymous> (src/hooks/useMessage/useMessage.test.tsx:8:1)
```

### Problem description:

Both importing from `@testing-library/react-hooks` and `@testing=library/react-hooks/dom` did not worked. Both of them couldn't find `renderHook` function

**Comment by joshuaellis** [comment]
Hi @SeungsuKim, are you able to provide us with a repo we can use to investigate this?

**Comment by SeungsuKim** [comment]
@joshuaellis Sorry. I'm working on a private library. What information do you have to know more? Please ask me

**Comment by joshuaellis** [comment]
Well, if I'm honest, the function is definitely exported from there, as I've just ran a test in one of my own repos using the set up you have, `5.1.0`, `react-dom` etc and the test passes as expected since it's an import issue we really need a minimal working example of the bug.

**Comment by SeungsuKim** [comment]
Okay. I'll try to make a reproduceable repository. But before that, do you know any possible reason for this error? Like react version or so. I've configured this project by ejecting from a CRA app.

**Comment by joshuaellis** [comment]
I can't think of one, like I said my project is setup the same way in regards to react version etc. Although it being ejected from CRA shouldn't make a difference, but maybe it does? I don't often use CRA, when you eject do you get access to the jest version, the jest config etc?

**Comment by SeungsuKim** [comment]
`jest` is already installed in CRA. Thus after ejection, `jest` version is the same as the CRA's `jest` version which is in my case `26.6.0`.

**Comment by mpeyper** [comment]
I've just tried setting up a project that uses the same version and ejecting CRA.  I created the same test and stubbed out `useMessage` so the test would pass and I used `new InMemoryCache()` for the `cache` value passed to `MockedProvider`.

The test was able to import `@testing-library/react-hooks/dom (and without `/dom`) and the test passes:

![image](https://user-images.githubusercontent.com/23029903/110205051-78cb1200-7eca-11eb-9d84-340bc6b29169.png)

I'm not sure what it could be that causing it not import correctly for your.  Any non-standard babel plugins?  Have you tried removing the `yarn`/`npm` lock file and `node_modules` and re-installing?

**Comment by mpeyper** [comment]
Closing this now.  Happy to reopen if there is more info or conversation to be had.

**Comment by benhalverson** [comment]
Hello, @mpeyper I also have this error. Here's a repo on the nodejs.dev repo 
The error is `TypeError: (0 , _react.renderHook) is not a function`
https://github.com/nodejs/nodejs.dev/runs/8266491940?check_suite_focus=true
Code is here.
https://github.com/nodejs/nodejs.dev/pull/2715/files#diff-8520a53e05c6076b3b47f9f81de3c23ddfa247cb1f98523f0e35d34181a27644

**Comment by mpeyper** [comment]
Hey @benhalverson,

it [looks like](https://github.com/nodejs/nodejs.dev/blob/40c6f1f3fdd0796cc35b2d0c1554eae6c2bc52bb/package.json) you are using `@testing-library/react` and not this package (`@testing-library/react-hooks`). Please [search for and/or raise and issue](https://github.com/testing-library/react-testing-library/issues) with them instead.
