### ISSUE TITLE
Cannot find module 'filter-console' from 'node_modules/@testing-library/react-hooks/lib/core/console.js'

### ISSUE THREAD

**Issue by ohardy** [testing-library/react-hooks-testing-library#629]
- `react-hooks-testing-library` version: 7.0.0
- `react` version: 17.0.2
- `react-dom` version (if applicable): 17.0.2
- `react-test-renderer` version (if applicable): 17.0.2
- `node` version: 16.2.0
- `npm` (or `yarn`) version: 7.13.0

### What you did:

Just upgraded to last version (7.0.0) and this issue just appear

### What happened:

```
  ● Test suite failed to run

    Cannot find module 'filter-console' from 'node_modules/@testing-library/react-hooks/lib/core/console.js'

    Require stack:
      node_modules/@testing-library/react-hooks/lib/core/console.js
      node_modules/@testing-library/react-hooks/lib/index.js
      [path]/__tests__/fileToTest.test.ts

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:311:11)
      at Object.<anonymous> (node_modules/@testing-library/react-hooks/lib/core/console.js:11:45)
```

Maybe it's related to this merge https://github.com/testing-library/react-hooks-testing-library/pull/624 no ?

Thanks

**Comment by mpeyper** [comment]
It's almost certainly related to #624, except that change removes the import for `filter-console` all together, so it shouldn't be trying to find it at all.

Can you try removing `node_modules/@testing-library/react-hooks` and reinstalling it?

I'll also try to reproduce it locally.

**Comment by ohardy** [comment]
So sorry @mpeyper, you are right, cleaning everything and doing npm install again fixed that, closing this.

**Comment by mpeyper** [comment]
Glad it was just that, otherwise I'd have to debug our whole release pipeline 😅
