### ISSUE TITLE
waitForValueToChange: ReferenceError MessageChannel is not defined

### ISSUE THREAD

**Issue by ahfarmer** [testing-library/react-hooks-testing-library#647]
- `react-hooks-testing-library` version: Tried 6.0.0 and 7.0.1
- `react` version: Tried 16.12.0, 16.14.0, and 17.0.1
- `react-dom` version (if applicable): Always kept the same as react version
- `react-test-renderer` version (if applicable): Always kept the same as react version
- `node` version: v14.15.5
- `npm` (or `yarn`) version: yarn 1.22.10

### Relevant code or config:

```js
    const x = renderHook(() => useMyCustomHook());
    await x.waitForValueToChange(() => x.result);
```

Also tried:

```js
    const x = renderHook(() => useMyCustomHook());
    return x.waitForValueToChange(() => x.result).then(() => {
       // do nothing
    });
```

### What happened:

```
  MyCustomHook
Warning: This browser does not have a MessageChannel implementation, so enqueuing tasks via await act(async () => ...) will fail. Please file an issue at https://github.com/facebook/react/issues if you encounter this warning.
    1) myfirsttest


  0 passing (1s)
  1 failing

  1) MyCustomHook
       myfirsttest:
     ReferenceError: MessageChannel is not defined
      at enqueueTaskImpl (webpack:///./node_modules/react-test-renderer/cjs/react-test-renderer.development.js?:14656:23)
      at enqueueTask (webpack:///./node_modules/react-test-renderer/cjs/react-test-renderer.development.js?:14663:10)
      at flushWorkAndMicroTasks (webpack:///./node_modules/react-test-renderer/cjs/react-test-renderer.development.js?:14893:5)
      at eval (webpack:///./node_modules/react-test-renderer/cjs/react-test-renderer.development.js?:14974:11)
```

### Research:

Looks like a similar issue in React has a workaround here: https://github.com/facebook/react/issues/20756#issuecomment-780927519

I tried that workaround and it didn't help. Also that workaround looks like it is for Node 15 and I am on Node 14.

The problem only seems to happen if I use `await`.

**Comment by mpeyper** [comment]
Hi @ahfarmer,

Can you provide some more details on how you are running the tests. I can see `webpack` so presumably you are bundling. Are you running the tests in a browser or still in node?

Another things to try is using the `@testing-library/react-hooks/dom` import. I've found some of the "fixes" in react only work in `react-dom` and `react-test-renderer` gets forgotten/ignored.

**Comment by ahfarmer** [comment]
Thanks for the response @mpeyper  ! 

I actually worked around this issue for the time being by updating Node from `14.15.5` to `v16.4.2`.

If I'm not able to update node everywhere I'll give the `/dom` import a try.
