### ISSUE TITLE
Pass an array of wrappers compared to just a single one

### ISSUE THREAD

**Issue by fredrikssongustav** [testing-library/react-hooks-testing-library#670]
### Describe the feature you'd like:

(relevant documentation: https://react-hooks-testing-library.com/usage/advanced-hooks)

Today it's possible to apply a wrapper as

```js
import { renderHook, act } from '@testing-library/react-hooks';
import { CounterStepProvider, useCounter } from './counter';

test('should use custom step when incrementing', () => {
  const wrapper = ({ children }) => (
    <CounterStepProvider step={2}>{children}</CounterStepProvider>
  );
  const { result } = renderHook(() => useCounter(), { wrapper });

  act(() => {
    result.current.increment();
  });

  expect(result.current.count).toBe(2);
});
```

I would like a feature that allow passing an array of unique wrappers

```js
import { renderHook, act } from '@testing-library/react-hooks';
import { CounterStepProvider, useCounter } from './counter';

test('should use custom step and custom letter when incrementing', () => {
  const wrapper = ({ children }) => (
    <CounterStepProvider step={2}>{children}</CounterStepProvider>
  );

  const secondWrapper = ({ children }) => (
    <LetterProvider letter={'A'}>{children}</LetterProvider>
  );

  const { result } = renderHook(() => useCounter(), {
    wrappers: [wrapper, secondWrapper],
  });

  act(() => {
    result.current.increment();
  });

  expect(result.current.count).toBe(2);
});
```

Compared to how we'd do it today:

```js
import { renderHook, act } from '@testing-library/react-hooks';
import { CounterStepProvider, useCounter } from './counter';

test('should use custom step and custom letter when incrementing', () => {
  const wrapper = ({ children }) => (
    <LetterProvider letter={'A'}>
      <CounterStepProvider step={2}>{children}</CounterStepProvider>
    </LetterProvider>
  );

  const { result } = renderHook(() => useCounter(), {
    wrapper,
  });

  act(() => {
    result.current.increment();
  });

  expect(result.current.count).toBe(2);
});
```

### Suggested implementation:

Looping over the array of wrappers and applying them one by one, recursive magic:

```js
type ApplyWrapperProps = {
  wrappers: React.FC[],
};

const ApplyWrapper: React.FC<ApplyWrapperProps> = ({ wrappers, children }) => {
  const Wrapper = wrappers[0];

  if (wrappers.length === 1) {
    return <Wrapper>{children}</Wrapper>;
  }

  return (
    <ApplyWrapper wrappers={wrappers.splice(1)}>
      <Wrapper>{children}</Wrapper>
    </ApplyWrapper>
  );
};

export const calculateWrappers = (wrappers: React.FC[]): React.FC => {
  return ({ children }) => (
    <ApplyWrapper wrappers={wrappers}>{children}</ApplyWrapper>
  );
};
```

### Teachability, Documentation, Adoption, Migration Strategy:

I think `wrapper` vs `wrappers` must be exclusive, it can be the one or the other, aside from that I think it's something that'd make it convenience for people working on larger applications.

**Comment by joshuaellis** [comment]
Hi @fredrikssongustav, 

I think it'd be really useful to understand why,

```js
  const wrapper = ({ children }) => (
    <CounterStepProvider step={2}>{children}</CounterStepProvider>
  );

  const secondWrapper = ({ children }) => (
    <LetterProvider letter={'A'}>{children}</LetterProvider>
  );

  const { result } = renderHook(() => useCounter(), {
    wrappers: [wrapper, secondWrapper],
  });
```

is better, or more preferable than the usual compositional method:

```js
  const wrapper = ({ children }) => (
    <LetterProvider letter={'A'}>
      <CounterStepProvider step={2}>{children}</CounterStepProvider>
    </LetterProvider>
  );

  const { result } = renderHook(() => useCounter(), {
    wrapper,
  });
```

Because, for me on first glance, I can't see why the former is better than the latter, and I feel like it sort of breaks the paradigmatic react approach of declarative writing...

**Comment by fredrikssongustav** [comment]
> Because, for me on first glance, I can't see why the former is better than the latter, and I feel like it sort of breaks the paradigmatic react approach of declarative writing...

Hmm.. I opened this issue as I thought it'd be a pattern that re-iterates in other's projects too. I'm starting to realise though that the idea of using supporting wrapping functions such as `secondWrapper` is probably unique to our project. The reason we have them is primarily due to how we test our React components–in which case it's very convenient to have wrapping functions that apply default states for e.g. locale, theming, ..., that you typically don't care about when testing business logic. In the case for hooks you're right about _declarative writing_ and we should adapt that in how we test our hooks instead. 

Thanks for the quick response!
