### ISSUE TITLE
Tests takes too long

### ISSUE THREAD

**Issue by VGamezz19** [testing-library/react-hooks-testing-library#702]
- `react-hooks-testing-library` version: ^7.0.2
- `react` version: ^17.0.1
- `react-dom` version (if applicable): ^17.0.1
- `react-test-renderer` version (if applicable): ^16.9.0
- `node` version: v14.13.1
- `npm` (or `yarn`) version: 7.10.0

### Relevant code or config:

Thats my regular tests, probably im doing bad

```js
// useWorkOrder.test.js
import { workOrders } from 'services';

jest.mock('services');

function mockWorkOrderServiceGetById() {
  workOrders.getById.mockResolvedValue({ data:  { id: 1, reference: 'ref' });
}

...

 it('retrieve an existing workOrder on getData when id', async () => {
    mockWorkOrderServiceGetById();

    const { result, waitForNextUpdate } = renderHook(() => useWorkOrder(ID));

    await waitForNextUpdate();

    expect(workOrders.getById).toBeCalled();

    expect(result.current.workOrder.reference).toBe(data.reference);
  });
...
```

```js
// useWorkOrder.js
...

export function useWorkOrder(id) {
...

  useEffect(() => {
    async function getData() {
        const response = await workOrders.getById(id);

        if (response) {
          setWorkOrderData(response.data || []);
        }
    }

    id && getData();
  }, [id]);
...

  return { workOrder: workOrderData, ... };
}
```
### What you did:

`react-scripts test --watchAll=false`

### What happened:

I have 107 tests like above and it takes between 165/300 seconds run them all.

### Reproduction:

I have not added any extra configuration, just what CRA gives and your [installation](https://github.com/testing-library/react-hooks-testing-library/blob/main/docs/installation.md)

### Problem description:

I feel like there is something wrong, Is it expected to take so long? probably im missing some configurations, or my async tests mess up the runner.

P.S: Im using Windows 

### Suggested solution:

don't have any, sorry

**Comment by mpeyper** [comment]
Hi @VGamezz19,

Sorry for taking so long to get to this.  I think there must be something else going on to slow your tests down as when I set up an example that runs the shown test (as best I can to make up what `workOrders.getById(id)` looks like), it runs it 107 times in no time at all:

![image](https://user-images.githubusercontent.com/23029903/134910329-cfebb0a0-6d8c-4b89-8720-cf6dc5669125.png)

Perhaps there is some particularly slow `beforeEach`/`afterEach` blocks that are running in between each test?

**Comment by VGamezz19** [comment]
hey @mpeyper  ty for your time! <3 

thats what workOrder.getById is

```js
import { workOrders } from 'services';

jest.mock('services');

function mockWorkOrderServiceGetById() {
  workOrders.getById.mockResolvedValue({ data:  { id: 1, reference: 'ref' });
}
```

Also, i did check and i dont have any beforeEach/afterEach block code

**Comment by mpeyper** [comment]
I'm not seeing such a severe time when I run the tests in that repo:

![image](https://user-images.githubusercontent.com/23029903/135007399-f9f040da-aa8b-4cdc-92c6-f9d6e3fb8e4b.png)

Only 5 seconds reported by `jest` and 6 seconds total time for the `npm` script.

**Comment by VGamezz19** [comment]
hey @mpeyper  tnx for your time <3

Im freaking out... I see that your node version is up than mine, so I did update node and npm, then remove `node_modules` and `-lock.json`, run `npm install --save --legacy-peer-deps` and this what happends...

![image](https://user-images.githubusercontent.com/14943217/135035866-bfa9e655-d649-4842-883b-3eabbf535f7e.png)

Im guessing that there is something wierd on windos/node/npm. This logs tells you something? could be related?

> runing `npm i` without --legacy-peer-deps or --force 
```sh
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: engloba-cmms-web@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.3.0 || ^16.0.0" from react-swipeable-views@0.13.9
npm ERR! node_modules/react-swipeable-views
npm ERR!   react-swipeable-views@"^0.13.9" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\v.gamez\AppData\Local\npm-cache\eresolve-report.txt for a full report.
```

> first time runing `npm i` on windows
```sh
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
```
