### ISSUE TITLE
difficulties with initialProps while testing rerender with different set of few arguments

### ISSUE THREAD

**Issue by skyboyer** [testing-library/react-hooks-testing-library#743]
Let's assume simple synthetic hook I'd like to test:

```
function useOnChange(value, onChange) {
  const recentOnChangeRef = useRef(onChange);
  recentOnChangeRef.current = onChange;
  useEffect(() => {
    recentOnChangeRef.current(value);
  }, [value]);
}
```

So I'd like to test whether re-rendering with different `value` triggers `onChange` I pass. So far I've succeeded only with 

```
const onChange = jest.fn();
const { rerender } = renderHook(
  (initialProps) => useOnChange(...initialProps),
  {
    initialProps: ['1', onChange],
  }
);
rerender(['2', onChange]);
expect(onChange).toHaveBeenCalledTimes(2);
expect(onChange).toHaveBeenLastCalledWith('2');
```

But you see how `rerender()` call differs from how hook is actually called - I have to pass array of arguments while using hook in component I actually pass arguments as usual.

Is it the only approach or do I overcomplicate thing and there is a better solution?

If it's expected and the only way, I'm willing to make MR to highlight this in docs, but before that I want to ensure I don't misuse `renderHook` in any way.

**Comment by mpeyper** [comment]
Hi @skyboyer,

Sorry, for the delay in getting to this.  What you have is fine, however, the intended way for `initialProps` to be used with multiple arguments is to use destructuring like so:

```ts
const onChange = jest.fn();
const { rerender } = renderHook(
  ({ value, onChange }) => useOnChange(value, onChange),
  {
    initialProps: { value, '1', onChange },
  }
);
rerender({ value: '2', onChange });
expect(onChange).toHaveBeenCalledTimes(2);
expect(onChange).toHaveBeenLastCalledWith('2');
```

In this case, passing `onChange` is also optional as it does not change between renders, so you could also simplify to:

```ts
const onChange = jest.fn();
const { rerender } = renderHook(
  ({ value }) => useOnChange(value, onChange),
  {
    initialProps: { value, '1' },
  }
);
rerender({ value: '2' });
expect(onChange).toHaveBeenCalledTimes(2);
expect(onChange).toHaveBeenLastCalledWith('2');
}
```

I hope that helps.

I don't want to be too prescriptive in the docs on the exact syntax to use here as a lot boils down to personal preference.  I'm happy to review any suggestions you may have to improve [the docs](https://react-hooks-testing-library.com/usage/basic-hooks#props) though, if you think there is something missing that would have helped.

**Comment by mycarrysun** [comment]
@mpeyper 

Does this basically mean that renderHook does not work when you have multiple parameters for your hook? I was trying to create a hook that has multiple parameters and it is throwing a typescript error. I think the actual types for renderHook should be like this:

```ts
export type ReactHooksRenderer = {
  renderHook: <TProps extends [], TResult>(
    callback: (...props: TProps) => TResult,
    options?: RenderHookOptions<TProps>
  ) => RenderHookResult<TProps, TResult>
  act: Act
  cleanup: () => Promise<void>
  addCleanup: (callback: CleanupCallback) => () => void
  removeCleanup: (callback: CleanupCallback) => void
  suppressErrorOutput: () => () => void
}
```

And then you would need to pass in your `initialProps` as an array instead. Basically in its current state, it looks like we can't test hooks with multiple parameters without this change.

**Comment by mpeyper** [comment]
No, as mentioned above, the intended usage for multiple arguments is to pass a single value and destructure it in the callback and pass through the values to your hook.

Think of the callback like a component. There’s only a single props argument with a key per prop passed to the component. If you want to pass the component props to you hook, you have to take them from the props object.

**Comment by mycarrysun** [comment]
> No, as mentioned above, the intended usage for multiple arguments is to pass a single value and destructure it in the callback and pass through the values to your hook.
> 
> Think of the callback like a component. There’s only a single props argument with a key per prop passed to the component. If you want to pass the component props to you hook, you have to take them from the props object.

That's not the spec for hooks though. You can pass multiple parameters to a hook according to the react framework. After all its just a function. There's no limit to the amount of parameters. https://react.dev/reference/rules/rules-of-hooks

Even in the deprecated docs site they give an example of a custom hook `useReducer` with multiple arguments: https://legacy.reactjs.org/docs/hooks-custom.html.

**Comment by mpeyper** [comment]
I’m a bit confused by what your issue is here. The `renderHook` callback is not a hook, but rather a body of a component (i.e. a safe place to call your hook).

Perhaps if you shared an example of a hook you are trying to test I can help show how to call it within the `renderHook` callback?

**Comment by mycarrysun** [comment]
Let's use the example from the old docs `useReducer`. Here is the definition:

```js
function useReducer(reducer, initialState) {
  const [state, setState] = useState(initialState);

  function dispatch(action) {
    const nextState = reducer(state, action);
    setState(nextState);
  }

  return [state, dispatch];
}
```

Now, in my opinion you should be able to pass all those parameters into the hook with `renderHook` using `initialProps` like so:
```js
describe('test example', () => {
  it('doesnt work like this', () => {
    const reducerMock = jest.fn();
    const { result } = renderHook(useReducer, {
      initialProps: [reducerMock, []]
    });
    
    const [state, dispatch] = result.current;
    expect(state).toBe([]); // this will fail because its undefined
  });
});
```

For this to work you'll need to spread the `hookProps` into the `render` function here https://github.com/testing-library/react-hooks-testing-library/blob/main/src/core/index.ts#L59. The same problem exists with `rerenderHook` here https://github.com/testing-library/react-hooks-testing-library/blob/main/src/core/index.ts#L63.

What essentially happens is the array from my example will be passed in as the first parameter so the `reducer` will now no longer be a function like it expects, and the `initialState` will be `undefined`.

**Comment by mpeyper** [comment]
So the misunderstanding here is that you believe the first argument of `renderHook` is where you pass the hook you are testing, and while that might work for simple hooks, it’s not actually what it is intended to be. As mentioned above, it’s actually to simulate the body of a component so you can call your hook as you would in your components:

```ts
describe('test example', () => {
  it('doesnt work like this', () => {
    const reducerMock = jest.fn();
    const { result } = renderHook(([reducer, deps]) => useReducer(reducer, deps), {
      initialProps: [reducerMock, []]
    });
    
    const [state, dispatch] = result.current;
    expect(state).toBe([]); // this will fail because its undefined
  });
});
```

We typically suggest using an object instead of an array for passing and destructing the props (simply because it looks more like component props) but I kept the array here to minimise the changes from your example.

If we were really testing this, we probably wouldn’t pass these props through `initialProps` at all and just reference them in the callback, which is perfectly acceptable if you don’t need to change the props with `rerender` later:


```ts
describe('test example', () => {
  it('doesnt work like this', () => {
    const reducerMock = jest.fn();
    const { result } = renderHook(() => useReducer(reducerMock, []));
    
    const [state, dispatch] = result.current;
    expect(state).toBe([]); // this will fail because its undefined
  });
});
```

Finally, please, please don’t destructure `result.current` in your tests. I know it’s a bit cumbersome to type it out all the time, but it leads to so many issues in tests because the values get locked in you test function and won’t get updated if the hook state changes (only the reference inside `result.current` changes, not your reference to the old value).

Hope that helps and let me know if anything needs more explanation.

**Comment by mycarrysun** [comment]
> So the misunderstanding here is that you believe the first argument of renderHook is where you pass the hook you are testing, and while that might work for simple hooks, it’s not actually what it is intended to be.

That indeed would be the misunderstanding - can you elaborate on this a bit further? I'm not sure I'm following how `([reducer, deps]) => useReducer(reducer, deps)` would be simulating how a component calls the hook.

**Comment by mycarrysun** [comment]
> Finally, please, please don’t destructure result.current in your tests.

Sorry force of habit lol I know about those issues which I almost put a comment to mention but anyways, thanks for the heads up

**Comment by mpeyper** [comment]
I just meant that it’s a callback that is executed inside the body of a component (we literally construct a component internally) so there is a safe context for you to execute your hooks in. If we rewrite the call like this, it _looks_ more like a component:

```ts
const reducerMock = jest.fn();
const { result } = renderHook(
  (props) => {
    const [state, dispatch] = useReducer(props.reducer, props.deps);
    return { state, dispatch }; // could just return the above but this make dealing with the values easier for assertions
  },
  { initialProps: { reducer: reducerMock, deps: [] } }
);

expect(result.current.state).toBe([]); // not sure why you are expecting an empty array here, but going with it for this examples 
```

So while not exactly like a component (it returns state instead of jsx) the callback looks similar to a component and has the same execution context as one, allowing you to call the hook like you would in a real component. You can also do whatever transforms are necessary inside the callback to support your test case, or even string together multiple hook calls if you have some that are meant to work together in some way (I’m not recommending coupling your hooks together like this, but I’ve certainly seen it done).
