### ISSUE TITLE
Unable to test custom hooks using Recoil's setState

### ISSUE THREAD

**Issue by airtoxin** [testing-library/react-hooks-testing-library#746]
- `react-hooks-testing-library` version:7.0.2
- `react` version:17.0.2
- `react-dom` version (if applicable):17.0.2
- `react-test-renderer` version (if applicable): NA
- `node` version:v16.13.0
- `npm` (or `yarn`) version:8.1.0(yarn:1.22.10)

#### `counter.js`

```js
import { atom, useSetRecoilState } from "recoil";

export const CounterState = atom({
  key: "CounterState",
  default: 0
});

export const useIncrement = () => {
  const setCounter = useSetRecoilState(CounterState);
  const increment = useCallback(() => setCounter((c) => c + 1), [setCounter]);

  return {
    increment
  };
};
```

#### `counter.test.js`

```js
import { renderHook, cleanup, act } from "@testing-library/react-hooks";
import { RecoilRoot, useRecoilState } from "recoil";
import { useIncrement, CounterState } from "../useHello";

afterEach(cleanup);

test("sample", () => {
  const wrapper = ({ children }) => <RecoilRoot>{children}</RecoilRoot>;

  const counterState = renderHook(() => useRecoilState(CounterState), {
    wrapper
  });
  expect(counterState.result.current[0]).toBe(0);
  act(() => counterState.result.current[1](10));
  // Normal setRecoilState works
  expect(counterState.result.current[0]).toBe(10);

  const increment = renderHook(() => useIncrement(), {
    wrapper
  });
  act(() => increment.result.current.increment());
  // custom setState not work
  expect(counterState.result.current[0]).toBe(11);
});
```

### What you did:

I would like to write a test for custom hooks using recoil's setState function.
I need to use the raw recoilState and read out the recoilState, since the function using setState alone cannot check if the value is actually set.
The setState function read from useRecoilState works fine, but when I try to test the result of custom hooks that use the setState function read from useSetRecoilState, the recoilState is not updated.

### What happened:

The RecoilRoot provides a consistent CounterState throughout the application, but it seems to be disconnected in the test code.
It is possible that the CounterState used by the useIncrement under test and the CounterState used by the useRecoilState for verification are two different things, causing the test to fail.

### Reproduction:

See relevant code

### Problem description:

With the current behavior, it seems that all custom hooks that return only Recoil setXXX callbacks cannot be tested.

**Comment by mpeyper** [comment]
Hi @airtoxin,

This is actually working as intended.  Each call to `renderHook` is creating a distinct react root for the hook to run in, so there are actually 2 seperate instances of `RecoilRoot` at play here.  If you changed `useIncrement` to be

```ts
const useIncrement = () => {
  const [tmp] = useRecoilState(CounterState);
  console.log('current', tmp);
  const setCounter = useSetRecoilState(CounterState);
  const increment = useCallback(() => setCounter((c) => {
    console.log('updating', c, '->', c + 1);
    return c + 1;
  }), [setCounter]);

  return {
    increment
  };
};
```

you should see that the logs display are updating a the counter state from `0` to `1` when your hook is used, not the previously set `10` of the other instance.

If you do _need_ to have a shared root component for your tests, you can call both hooks within the same `renderHook` callback and return the different bits and pieces you need for you test, something like:

```ts
test('sample', () => {
  const wrapper = ({ children }) => <RecoilRoot>{children}</RecoilRoot>

  const counterState = renderHook(
    () => {
      const [state, setState] = useRecoilState(CounterState)
      const { increment } = useIncrement()
      return {
        state,
        setState,
        increment
      }
    },
    {
      wrapper
    }
  )
  
  expect(counterState.result.current.state).toBe(0)

  act(() => counterState.result.current.setState(10))
  // Normal setRecoilState works
  expect(counterState.result.current.state).toBe(10)

  act(() => counterState.result.current.increment())
  // custom setState now also work
  expect(counterState.result.current.state).toBe(11)
})
```

**Comment by airtoxin** [comment]
Oh, I see.
I guess I should have called multiple hooks in the renderHook callback. Thank you very much!
