### ISSUE TITLE
Update Peer Dependencies

### ISSUE THREAD

**Issue by martin-badin** [testing-library/react-hooks-testing-library#782]
Please, I think it is needed to update react version in peerDependencies section to avoid console warnings when I want to install this library. devDependencies are updated to the latest version of react but peerDependencies are not.

```
warning "@testing-library/react-hooks > react-error-boundary@3.1.1" has unmet peer dependency "react@>=16.13.1".
warning " > @testing-library/react-hooks@7.0.2" has unmet peer dependency "react@>=16.9.0".
```

https://github.com/testing-library/react-hooks-testing-library/blob/main/package.json#L78-L80

- `react-hooks-testing-library` version: 7.0.2
- `react` version: 17.0.2
- `react-dom` version (if applicable): 17.0.2
- `react-test-renderer` version (if applicable): 17.0.2
- `node` version: 12.27.7
- `yarn` version: 1.22.17

**Comment by mpeyper** [comment]
Hi @martin-badin, what is giving this peer dependency warning? NPM/yarn?

The reason I ask is that `>=16.9.0` is a valid semver range that includes `17.0.2` (you can check which versions match [here](https://semver.npmjs.com/)) so I'm not sure why you would be seeing that error unless an unsupported version is being installed as the peer (e.g. from some other dependency).

What does `npm ls react` (or the yarn equivalent) show?

**Comment by martin-badin** [comment]
Hi @mpeyper. I saw the warning if I installed the latest version of this library for the first time. If I reinstalled dependencies in my project I don't see the warning. I looked in yarn.lock and there is the correct version of React (17.0.2). It seems it is fine and we can close this issue.
