### ISSUE TITLE
add expectStableFunctionExports() matcher

### ISSUE THREAD

**Issue by pke** [testing-library/react-hooks-testing-library#783]
### Describe the feature you'd like:

If I understand it correctly exports from hooks should be "identity stable" to not cause unnecessary render loops.
I have seen my hooks in my current team project where especially exported functions are not stable.
This causes many (sometimes infinite) render loops.

I caught some of the culprits with the suggested implementation below. Its just a first idea, which assumes that exports always have the same shape (object vs array and same keys/items).

Of course there are legitimate reasons to change functions because some dependencies so this check needs to be done on a per case base.

### Suggested implementation:

```ts
function expectStableCallbacks(result: any, rerender: () => void) {
  const previousFunctions = Object.values(result.current).filter((item) => typeof item === "function")
  rerender()
  const nowFunctions = Object.values(result.current).filter((item) => typeof item === "function")
  expect(nowFunctions).toHaveLength(previousFunctions.length)
  expect(nowFunctions).toEqual(previousFunctions)
}
```

### Describe alternatives you've considered:

Teach team mates about function/object identity ;)

**Comment by mpeyper** [comment]
Hi @pke,

Thanks for taking the time to put this together, but I don't think we will be implementing any features like this, where we optimise for very specific hook designs and use cases.

The issue with us trying to implement these sorts of utilities is that not all hooks return objects.  Some just return a function, some return arrays with functions in some positions and some return very complex structures that could have functions nested in completely arbitrary locations.  As such, it would be very difficult for us to cater to everyones unique requirements so instead, I think it's best kept in userland where people can test their own requirements using their regular tasting utilities.

> If I understand it correctly exports from hooks should be "identity stable" to not cause unnecessary render loops.

I just want to also address your starting position with this as it is fairly common advice and some people/teams dogmatically enforce this without putting time and effort into actually measuring the impacts of it.  Essentially, the returned value for each custom hook and how that result is consumed should be evaluated on a case-by-case basis to determine if stable references are necessary.

While there are certainly cases where you do want to ensure function reference are stable in a hook's results, there are lots of cases where it does not trigger additional renders or just generally doesn't matter given the component they are being passed to (i.e. the memoization costs more than the render).  Kent C. Dodds has [a great article](https://kentcdodds.com/blog/usememo-and-usecallback) about this if you want to dig in further.

**Comment by pke** [comment]
Thanks for your answer!
>  Essentially, the returned value for each custom hook and how that result is consumed should be evaluated on a case-by-case basis to determine if stable references are necessary.

I evaluated all our hooks and usages of exported values and all of them cause problems when not stable, cause they are used as dependencies to other hooks.

I know Ken's article and I give it out as reference to fellow team members it just doesn't fully address the issue we have with functions as dependencies to other hooks.

I will further refine my function and use it in our tests for now and maybe publish it as an additional package later.

Keep up the good work that helps us testing hooks better than before!
