### ISSUE TITLE
How to test async hooks, that do not change any of their exports?

### ISSUE THREAD

**Issue by pke** [testing-library/react-hooks-testing-library#785]
I have a hook that performs several async (fetches) operations but in the default hook setting it doesn't the hook does not change any of its exported values.

How would one test such hook (just smoke test, that it doesn't crash) and wait for all async operations to finish. 
None of the `waitFor*` functions seem to allow for such scenario to wait for all render cycles to finish, they all timeout.

Is there some trick to test such hooks?

**Comment by pke** [comment]
Consider this hook:

```ts
function hook() {
  const [data, setData] = useState(undefined)

  useEffect(() => {
    fetch(...).then(response => response.isOk && setData(() => ...)
  }, [])

  return {
    data,
    error,
  }
}
```
Initially `data` is undefined. The effect fetches data and only if the response is in the 200 range updated the data.
In my smoke tests I just want to see if the hook renders without error. Since this code above is a simplified version of my real hook lets say the mocked response (by default) is always in the 400er status range, so the `setUpdate` functionm is never called. However, the async `fetch` has been called upon hook mounting and I now need a way to wait for the fetch promise chain to complete.

Any idea how to achieve that (without mocking a 200 status response, which in my tests is not possible atm)?

**Comment by mpeyper** [comment]
Assuming that `error` value is not being set as part of the promise chain, then no, there isn't any utils provided by us that can hook into the promise resolution and wait for it to be done. This is a JavaScript problem, not a library problem. If the promise chain doesn't trigger a render or a side-effect, there is nothing for us to watch for. We don't even have a reference to the promise itself to add a `.finally` or something to.

In a situation like this, often the best you can do is have the test wait for a defined period of time (e.g. `setTimeout`) before moving on. This will generally lead to a slow, brittle and hard to maintain test, so I would advise against it unless you are out of options.

**Comment by pke** [comment]
Yeah, I am trying to figure out how I could update at least on internal value to wait for. Thanks!
