### ISSUE TITLE
Test for initial result from hook, before a setState update

### ISSUE THREAD

**Issue by penx** [testing-library/react-hooks-testing-library#797]
### Describe the feature you'd like:

If I have a hook that immediately calls setState, e.g.

```js
const useExample = () => {
  const [loading, setLoading] = useState(false);
  setLoading(true);
  return loading;
}
```

A React component that uses this hook would render twice, initially with the return value being `false` and then with the return value being `true`.

Say this was a bug, and that and I wanted to write a failing test to show this unexpected behaviour, i.e. that the initial value of `loading` returned from the hook should be `true`, I would expect the test to look like this and for it to fail:

```js
  const {result} = renderHook(()=> useExample());
  expect(result.current).toBe(true);
```

However this test passes, as the setState is resolved before the assertion.

I don't think it is currently possible to test for the `false` value that would ve received by the component on the initial render.

### Suggested implementation:

Please could you provide one of these 3 features:

- a way to prevent the hook updating before the assertion
- a way to log how many times the hook had rendered
- a way to find the initial, or previous return values of the hook

### Describe alternatives you've considered:

It would be possible to write a wrapping hook:

```js
  const render = jest.fn();
  const useWrapper = () => {
    const result = useExample()
    render(result);
    return result;
  }
  const {result} = renderHook(() => useWrapper());
  expect(result.current).toBe(true);
  expect(render).toHaveBeenCalledTimes(1);
```

...but it feels like something that should be available from the core API without writing a wrapping hook in the test.

**Comment by mpeyper** [comment]
Hi @penx,

`result.all` should be able to help you out here. It is an array of all the results returned from the hook function, not just the final value after the rendering has settled.

Just beware that what you are suggesting is teetering on the edge of focusing too much on implementation details which we generally try to avoid when using `@testing-library`. Try to frame your test cases as what the user sees and focus on that.
