### ISSUE TITLE
global configuration setter

### ISSUE THREAD

**Issue by teobler** [testing-library/react-hooks-testing-library#812]
### Describe the feature you'd like:

add an exported function for global configuration to override/setup default value.

#### Why

in some scenarios we may need to setup some config globally, like extend timeout for async utils.
But there is no way for these global setup. We can just set them one by one in each test.

### Suggested implementation:
we can maintain a global config to be default value, then we can get default values from this global config instead of setup each function.
Then user can call global config function to override default config or just pass custom params when using a specific function during testing.
the priority will be: custom params > global config

### Describe alternatives you've considered:

pass config params in each test.

### Teachability, Documentation, Adoption, Migration Strategy:

No migration actions required by users. All the changes should not break any feature for current behavior.
Just adding a new API for setup config globally.

byw, I would have a try to add this feature and document if we decide to add this feature after discuss:)

**Comment by teobler** [comment]
Hi @mpeyper,

Thanks for the context sharing, I will take a look about this PR before start it.

for global setting idea I'm just thinking if I need to align API style with testing library packages, like react-testing-library:
```javascript
  import { configure } from '@testing-library/react'
  
  configure({ asyncUtilTimeout: 10000 })
```

your concern is reasonable, but we can also add a section in doc to explain how to reset these configuration may like this:
```javascript
  import { configure } from '@testing-library/react'

  describe('some tests', () => {
    beforeAll(() => {
      configure({ asyncUtilTimeout: 5000 });
    })

    afterAll(() => {
      configure({ asyncUtilTimeout: 10000 });
    })
  })
```

both fine for me, waiting for decision😁

**Comment by teobler** [comment]
Hi @mpeyper any update for your prefer here?

**Comment by mpeyper** [comment]
Hey @teobler, sorry I missed the "waiting for decision" part of your previous message.

Given the release of React 18 now, it looks like [this MR](https://github.com/testing-library/react-hooks-testing-library/issues/812) will be merged very soon, so if RTL already has this functionality, then I don't think there is much value in us adding it now.

Sorry to waste your time and thoughts on it.

**Comment by teobler** [comment]
Hi @mpeyper,

cool, then this should be fine, and you may posted the wrong link lol.

anyway, I will close this issue in this case.

**Comment by douglasjunior** [comment]
How about of React Native future?

React Native projects dont use "@testing-library/react" or "@testing-library/dom", but use "@testing-library/react-native" and "@testing-library/react-hooks".
