### ISSUE TITLE
The version descriptors for @types/react and @types/react-dom are too permisive

### ISSUE THREAD

**Issue by thiniulian** [testing-library/react-hooks-testing-library#818]
- `react-hooks-testing-library` version: 7.0.2
- `react` version: 17.0.11
- `react-dom` version (if applicable): 17.0.11
- `react-test-renderer` version (if applicable):
- `node` version: 14

### What you did:

I ran an yarn install.

### What happened:

@types/react and @types/react-dom got a new version yesterday, they got updated to version 18.0 

### Reproduction:

Just run `yarn` and see the versions for @types/react and @types/react-dom update. These two packages got a new version update on 7th of April, 2022.

### Problem description:

The update to version 18.0 for those packages broke the functionality for other packages, for example, nextjs because it introduces a new definition for at least one type, breaking the builds.

### Suggested solution:

Use a more strict version resolution for those types until you have a version that supports React 18 and people interested in it would specifically install it.

**Comment by mpeyper** [comment]
This should be resolved in v8.0.0 where we no longer install type dependencies
