### ISSUE TITLE
TypeError: (0 , _reactTestRenderer.act) is not a function

### ISSUE THREAD

**Issue by cksal0805** [testing-library/react-hooks-testing-library#831]
Hi, I'm having a hard time writing the test code with react-hooks-testing-library.
Can you help me?
I'm sorry for my poor English.

**version**
- "react-test-renderer": "^18.1.0",
- "@testing-library/jest-dom": "^5.16.4",
- "@testing-library/react-hooks": "^8.0.0",

**code**
```ts
import { QueryClient, QueryClientProvider } from 'react-query';
import { renderHook } from '@testing-library/react-hooks';
import { useGetDataQuery, GetDataQueryType } from 'codegen/generated/graphql';
import graphqlRequestClient from 'utils/graphqlRequestClient';

const queryClient = new QueryClient();
const wrapper = ({ children }: {children: ReactChild}) => (
  <QueryClientProvider client={queryClient}>
    {children}
  </QueryClientProvider>
); 
const { result } = renderHook(() => useGetDataQuery<GetDataQueryType>(graphqlRequestClient, {}), {
  wrapper
});
```

**run**
```
yarn jest myTest
```

**error**
```js
TypeError: (0 , _reactTestRenderer.act) is not a function
```

**Comment by mpeyper** [comment]
It looks like you are trying to use React 18 (given the version of `react-test-renderer`. Is that correct?

This package is not going to support React 18 and you should rather import `renderHook` from the latest version of `@testing-library/react`. Check out [their docs](https://testing-library.com/docs/react-testing-library/api#renderhook) for more details.

**Comment by cksal0805** [comment]
@mpeyper Thanks. but, my react version is 17 😿

**Comment by mpeyper** [comment]
The your `react-test-renderer` version should match your react version.

**Comment by cksal0805** [comment]
@mpeyper oh, thanks! 🥳🥳🥳
