### ISSUE TITLE
TypeError: Cannot read property 'current' of undefined. In React v18 

### ISSUE THREAD

**Issue by RonaldCast** [testing-library/react-hooks-testing-library#842]
- `react-hooks-testing-library` version:^8.0.0"
- `react` version: ^18.1.0
- `react-dom` version (if applicable): ^18.1.0"
- `node` version: 14.17.4
- `npm` (or `yarn`) version: 6.14.14

### Problem description:

I have this error in React v18.1.0, but in React v17.0.2 work good.

![image](https://user-images.githubusercontent.com/24918679/169200671-cc6b643e-bec9-416b-b970-228b728f2829.png)

### Code 

This is my code that throws the error.

```
import { renderHook } from "@testing-library/react-hooks"
import useCounter from "../../hooks/useCounter"

describe("xxxxxxxxxxxxxxx", () => {

    test("xxxxxxxxxxxxxxxxxx", () =>{
        const r = renderHook(() => useCounter())

        console.log(r)
    })
})
```

**Comment by joshuaellis** [comment]
This library does not and will not support react 18. See https://github.com/testing-library/react-hooks-testing-library/issues/831#issuecomment-1112118476 for more information.
