### ISSUE TITLE
Migration to React 18

### ISSUE THREAD

**Issue by dryzhkov** [testing-library/react-hooks-testing-library#854]
### What is your question:

Is there existing documentation on how to migrate to React18? There seem to be a number of breaking changes. For example, `renderHook` in RTL v13 doesn't expose `waitForNextUpdate` - how should tests which use that utility helper be migrated?

**Comment by joshuaellis** [comment]
These questions should be directed to the testing-library/react library as this is a discussion on their version of the API implementation.

There were decisions to specifically not include some features of the API we had built out, so please, have the conversation in that repo with the relevant team ☺️

**Comment by agrohs** [comment]
At least would be helpful to link through @joshuaellis  - a shame to close here as its not as if this project is unrelated to react!
