### ISSUE TITLE
@testing-library/react-hooks does not support React 18 yet

### ISSUE THREAD

**Issue by syukronarie** [testing-library/react-hooks-testing-library#857]
### When I was trying to install @testing-library/react-hooks, it has only support for React 16 and 17, Please help to support React 18, thank you

![image](https://user-images.githubusercontent.com/36725290/173159942-af4ac104-d184-4c95-8d65-26ad6a28889e.png)

**Comment by mpeyper** [comment]
Please see [the note about React 18](https://github.com/testing-library/react-hooks-testing-library) in our README.
