### ISSUE TITLE
No support for React 18?

### ISSUE THREAD

**Issue by YarivGilad** [testing-library/react-hooks-testing-library#874]
Trying to get up and running using the example code from the docs.
Does react-hooks-testing-library have support or a workaround that works with **React 18**?

- `react-hooks-testing-library` version: 8.0.1
- `react` version: 18.2.0
- `react-dom` version: 18.2.0
- `node` version: 16.15.0
- `npm` version: 8.14.0

**Comment by YarivGilad** [comment]
So now **renderHook** and **act** are available in **@testing-library/react** ?
Shouldn't you deprecate this library? this is really misleading...

**Comment by mpeyper** [comment]
Hi, we have a [note in the README](https://github.com/testing-library/react-hooks-testing-library) explaining what is happening with react 18 and [an issue](https://github.com/testing-library/react-hooks-testing-library/issues/849) for officially deprecating this repo and the npm package. Please be patient as my time for OSS is all but gone and these tasks are very low priority for me.

**Comment by linxpo** [comment]
Still no support for the 18.2.0 ?

**Comment by ahmed-khlifi** [comment]
Still no support for the 18.2.0 ?

**Comment by mpeyper** [comment]
Hi @ahmed-khlifi, there are no plans to support React 18 or newer, as per the [note in the README](https://github.com/testing-library/react-hooks-testing-library). For React 18 support, you should migrate to `@testing-library/react`.

**Comment by ahmed-khlifi** [comment]
@mpeyper thanks for the clarification
