### ISSUE TITLE
Lib incompatible with react@18.2.0 version

### ISSUE THREAD

**Issue by saileerane** [testing-library/react-hooks-testing-library#966]
### What is this issue about:

The latest version of @testing-library/react-hooks v8.0.1 is not compatible with react@18.2.0
It will be great if this support is provided

**Comment by davidgoli** [comment]
`renderHook` has been moved to `@testing-library/react`, and importing from `@testing-library/react-hooks` is deprecated. You should update your imports accordingly.

**Comment by xobotyi** [comment]
yet it is not only imports, `@testing-library/react` version is incompatible with this one and requires rewriting most of test, not to say that it completely lacks `server` version

**Comment by joshuaellis** [comment]
We're aware of this, I think there's actually a note on the readme.
