### ISSUE TITLE
Update @types/react package to version 18

### ISSUE THREAD

**Issue by asifurrahaman754** [testing-library/react-hooks-testing-library#972]
- `react-hooks-testing-library`"^8.0.1":
- `react` "^18.0.0":
- `react-dom` "^18.0.0"
- `react-test-renderer` version (if applicable):
- `node` version: 18.13.0
- `npm` (or `yarn`) version: 8.19.3

### What you did:

Trying to install react-hook-form

### What happened:

![Screenshot 2024-04-15 at 11 43 49 AM](https://github.com/testing-library/react-hooks-testing-library/assets/66458004/f02bf137-ed8b-4828-a90c-1aab305caf1a)

### Problem description:

I am getting a lot of conflict error in my project while working with  @testing-library/react-hooks with other packages, By investigating the error i found you have a package @types/react that is not updated, so please update it to version 18

### Suggested solution:
Updating the @types/react to version 18 might solve this

**Comment by Tockra** [comment]
https://github.com/testing-library/react-hooks-testing-library?tab=readme-ov-file#a-note-about-react-18-support

**Comment by joshuaellis** [comment]
see [testing-library/react-hooks-testing-library#a-note-about-react-18-support](https://github.com/testing-library/react-hooks-testing-library?tab=readme-ov-file#a-note-about-react-18-support)
