### ISSUE TITLE
Update types/react & react & react-dom to support react 18

### ISSUE THREAD

**Issue by tarektarho** [testing-library/react-hooks-testing-library#976]
### What is your question:

Can you please update the the following dependencies:
- @types/reac
- react
- react-dom

I'm getting he following warning:
![Screenshot 2024-10-18 at 22 14 46](https://github.com/user-attachments/assets/bd628cf9-64c3-4f9d-88ca-650efb26d27c)

**Comment by MForMarlon** [comment]
This issue was already answered here: https://github.com/testing-library/react-hooks-testing-library/issues/972

**Comment by joshuaellis** [comment]
see https://github.com/testing-library/react-hooks-testing-library/issues/972 as said above.
