### ISSUE TITLE
Move to testing-library org and make scoped package

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/react-hooks-testing-library#99]
I could've sworn that this issue already existed, but I can't find it so here it is. I would like to formally invite you to bring this package into the testing-library org on GitHub and publish to the `@testing-library` scope under `@testing-library/react-hooks`.

I've sent you the invites etc. and you can learn more about the process of publishing to the scope here: https://github.com/testing-library/dom-testing-library/issues/260#issuecomment-497407055

Let me know if you have any questions or need assistance! Thanks!

**Comment by mpeyper** [comment]
Thanks.  I'll hopefully get onto this tonight.

**Comment by mpeyper** [comment]
I'm msotly done on this.  I've published `@testing-library/react-hook@1.0.0` (closely followed by `1.0.1` and `1.0.2` 😬) but I have not made any deprecated packages/warnings for `react-hooks-testing-library`, so I'll look at that next (another time).

The only thing is I seem to have lost some permissions (e.g. authorizings apps, viewing the settings, etc.) for this repo after transferring ownership.  Not sure I've set the teams up right or not, or what the missing pieces of that puzzle are.  perhaps you can double check them @kentcdodds?

**Comment by kentcdodds** [comment]
Fixed that @mpeyper! Thanks!

**Comment by mpeyper** [comment]
@kentcdodds nothings appears to have changed on my end.  Not sure what permissions I should have as part of an org, but I would have thought the "Settings" tab would still be visible?  I don't have any major need to change any settings or authorise any apps or anything at the moment, and I've still got push access and able to publish, so I'm not really blocked by this, but I'd like those permissions back at some point if it's possible.

**Comment by kentcdodds** [comment]
Sorry about that. It should be fixed now.

**Comment by mpeyper** [comment]
All good now 👍
